window.RESTAURANT_DATA = [
  {
    "id": "food-tokyo-seafood-buffet-dining-ginza-happo-1",
    "title": "Seafood Buffet Dining Ginza Happo",
    "region": "tokyo",
    "area": "Ginza / Shimbashi",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 8,000-9,999",
    "rating": 3.46,
    "tags": [
      "Yakiniku, sushi, izakaya",
      "Main tourist area",
      "Shimbashi"
    ],
    "note": "Ginza/Shimbashi visitor core.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130103/13292459/",
    "mapQuery": "Seafood Buffet Dining Ginza Happo, Ginza / Shimbashi, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-centre-the-bakery-2",
    "title": "CENTRE THE BAKERY",
    "region": "tokyo",
    "area": "Ginza / Yurakucho",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 2,000-2,999",
    "rating": 3.85,
    "tags": [
      "Bread, sandwich",
      "Main tourist area",
      "Ginza"
    ],
    "note": "Central Ginza stop.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130101/13157424/",
    "mapQuery": "CENTRE THE BAKERY, Ginza / Yurakucho, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-tokyo-en-3",
    "title": "Tokyo En",
    "region": "tokyo",
    "area": "Ginza",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 8,000-9,999",
    "rating": 3.85,
    "tags": [
      "Yakiniku",
      "Main tourist area",
      "Ginza"
    ],
    "note": "Central Ginza stop.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130101/13002566/",
    "mapQuery": "Tokyo En, Ginza, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-viron-marunouchi-ten-4",
    "title": "VIRON Marunouchi ten",
    "region": "tokyo",
    "area": "Marunouchi / Tokyo Station",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 1,000-1,999",
    "rating": 3.84,
    "tags": [
      "Bread, cake, cafe",
      "Main tourist area",
      "Marunouchi"
    ],
    "note": "Tokyo Station / Marunouchi visitor core.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1302/A130201/13043904/",
    "mapQuery": "VIRON Marunouchi ten, Marunouchi / Tokyo Station, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-wako-tea-salon-5",
    "title": "Wako Tea Salon",
    "region": "tokyo",
    "area": "Ginza",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 4,000-4,999",
    "rating": 3.81,
    "tags": [
      "Cafe, cake",
      "Main tourist area",
      "Ginza"
    ],
    "note": "Central Ginza stop.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130101/13009081/",
    "mapQuery": "Wako Tea Salon, Ginza, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-mentokoro-ginzasa-6",
    "title": "Mentokoro Ginzasa",
    "region": "tokyo",
    "area": "Ginza / Shimbashi",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.78,
    "tags": [
      "Ramen, tsukemen",
      "Main tourist area",
      "Ginza"
    ],
    "note": "Central Ginza/Shimbashi stop.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130103/13119563/",
    "mapQuery": "Mentokoro Ginzasa, Ginza / Shimbashi, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-la-boutique-de-joel-robuchon-marunouchi-7",
    "title": "La Boutique de Joel Robuchon Marunouchi",
    "region": "tokyo",
    "area": "Marunouchi / Tokyo Station",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 1,000-1,999",
    "rating": 3.78,
    "tags": [
      "Bread, cake, cafe",
      "Main tourist area",
      "Marunouchi"
    ],
    "note": "Tokyo Station / Marunouchi visitor core.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1302/A130201/13096409/",
    "mapQuery": "La Boutique de Joel Robuchon Marunouchi, Marunouchi / Tokyo Station, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-ginza-inaba-8",
    "title": "Ginza Inaba",
    "region": "tokyo",
    "area": "Ginza / Higashi-Ginza",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 30,000-39,999",
    "rating": 3.85,
    "tags": [
      "Japanese cuisine",
      "Main tourist area",
      "Higashi-Ginza"
    ],
    "note": "Central Ginza stop.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130101/13259495/",
    "mapQuery": "Ginza Inaba, Ginza / Higashi-Ginza, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-ginza-uchiyama-9",
    "title": "Ginza Uchiyama",
    "region": "tokyo",
    "area": "Ginza / Shintomicho",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 30,000-39,999",
    "rating": 3.77,
    "tags": [
      "Japanese cuisine",
      "Main tourist area",
      "Shintomicho"
    ],
    "note": "Ginza edge; still central.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130101/13002322/",
    "mapQuery": "Ginza Uchiyama, Ginza / Shintomicho, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-tonkatsu-narikura-10",
    "title": "Tonkatsu Narikura",
    "region": "tokyo",
    "area": "Suginami",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 6,000-7,999",
    "rating": 4.25,
    "tags": [
      "Tonkatsu",
      "Outside main tourist area",
      "Naritahigashi"
    ],
    "note": "Purpose trip west of central Tokyo.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1319/A131905/13236380/",
    "mapQuery": "Tonkatsu Narikura, Suginami, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-lature-11",
    "title": "LATURE",
    "region": "tokyo",
    "area": "Shibuya / Omotesando",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 10,000-14,999",
    "rating": 4.24,
    "tags": [
      "French",
      "Main tourist area",
      "Omote-Sando"
    ],
    "note": "Between Shibuya and Omotesando.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1303/A130301/13198692/",
    "mapQuery": "LATURE, Shibuya / Omotesando, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-watabe-12",
    "title": "Watabe",
    "region": "tokyo",
    "area": "Koishikawa / Bunkyo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 8,000-9,999",
    "rating": 4.09,
    "tags": [
      "Unagi, seafood, Japanese cuisine",
      "Outside main tourist area",
      "Koishikawa"
    ],
    "note": "North of central visitor loops; plan as a detour.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1310/A131003/13042184/",
    "mapQuery": "Watabe, Koishikawa / Bunkyo, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-japanese-cuisine-yamazaki-13",
    "title": "Japanese Cuisine Yamazaki",
    "region": "tokyo",
    "area": "Kyobashi / Tokyo Station",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 30,000-39,999",
    "rating": 4.09,
    "tags": [
      "Japanese cuisine, unagi",
      "Main tourist area",
      "Takaracho"
    ],
    "note": "Tokyo Station / Ginza-adjacent.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1302/A130202/13287123/",
    "mapQuery": "Japanese Cuisine Yamazaki, Kyobashi / Tokyo Station, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-raa-menya-shima-14",
    "title": "Raa Menya Shima",
    "region": "tokyo",
    "area": "Shibuya Honmachi / Nishi-Shinjuku",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "TBD",
    "rating": 4.07,
    "tags": [
      "Ramen, tsukemen",
      "Central, less touristy",
      "Honmachi"
    ],
    "note": "Central-ish but away from Shinjuku Station tourist zone.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1304/A130401/13247487/",
    "mapQuery": "Raa Menya Shima, Shibuya Honmachi / Nishi-Shinjuku, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-teuchi-soba-jiyu-san-15",
    "title": "Teuchi Soba Jiyu San",
    "region": "tokyo",
    "area": "Nakano / Eharacho",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 6,000-7,999",
    "rating": 4.05,
    "tags": [
      "Soba",
      "Outside main tourist area",
      "Eharacho"
    ],
    "note": "Northwest detour from the usual tourist zones.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1321/A132101/13025978/",
    "mapQuery": "Teuchi Soba Jiyu San, Nakano / Eharacho, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-homemade-ramen-muginawa-16",
    "title": "Homemade Ramen Muginawa",
    "region": "tokyo",
    "area": "Minami-Oi / Shinagawa",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 4.03,
    "tags": [
      "Ramen, tsukemen",
      "Outside main tourist area",
      "Minami-Oi"
    ],
    "note": "South of central Tokyo; plan around Shinagawa/Oimachi.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1315/A131502/13194812/",
    "mapQuery": "Homemade Ramen Muginawa, Minami-Oi / Shinagawa, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-aldebaran-17",
    "title": "ALDEBARAN",
    "region": "tokyo",
    "area": "Azabu-Juban / Roppongi",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 2,000-2,999",
    "rating": 3.97,
    "tags": [
      "Hamburger, creative, meat dishes",
      "Main tourist area",
      "Azabu-Juban"
    ],
    "note": "Roppongi/Azabu visitor area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1307/A130702/13278678/",
    "mapQuery": "ALDEBARAN, Azabu-Juban / Roppongi, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-chuka-soba-shibata-18",
    "title": "Chuka Soba Shibata",
    "region": "tokyo",
    "area": "Komae",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.97,
    "tags": [
      "Ramen",
      "Outside main tourist area",
      "Komae"
    ],
    "note": "Far west Tokyo; dedicated detour.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1326/A132603/13300645/",
    "mapQuery": "Chuka Soba Shibata, Komae, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-tonkatsu-nanaido-19",
    "title": "Tonkatsu Nanaido",
    "region": "tokyo",
    "area": "Jingumae / Omotesando",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "TBD",
    "rating": 3.94,
    "tags": [
      "Tonkatsu",
      "Main tourist area",
      "Jingumae"
    ],
    "note": "Harajuku/Omotesando visitor area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1306/A130603/13229075/",
    "mapQuery": "Tonkatsu Nanaido, Jingumae / Omotesando, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-tonkatsu-iwai-20",
    "title": "Tonkatsu Iwai",
    "region": "tokyo",
    "area": "Shiba Koen / Tokyo Tower",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 2,000-2,999",
    "rating": 3.91,
    "tags": [
      "Tonkatsu",
      "Main tourist area",
      "Shiba Koen"
    ],
    "note": "Near Tokyo Tower / Daimon.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1314/A131401/13170377/",
    "mapQuery": "Tonkatsu Iwai, Shiba Koen / Tokyo Tower, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-yaesu-unagi-hashimoto-21",
    "title": "Yaesu Unagi Hashimoto",
    "region": "tokyo",
    "area": "Yaesu / Tokyo Station",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 10,000-14,999",
    "rating": 3.9,
    "tags": [
      "Unagi",
      "Main tourist area",
      "Yaesu"
    ],
    "note": "Tokyo Station area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1302/A130202/13303042/",
    "mapQuery": "Yaesu Unagi Hashimoto, Yaesu / Tokyo Station, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-aigre-douce-22",
    "title": "AIGRE DOUCE",
    "region": "tokyo",
    "area": "Shimoochiai / Mejiro",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.88,
    "tags": [
      "Cake, macaroon",
      "Outside main tourist area",
      "Shimoochiai"
    ],
    "note": "Not the Shinjuku Station tourist area; plan as a pastry detour.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1305/A130502/13005641/",
    "mapQuery": "AIGRE DOUCE, Shimoochiai / Mejiro, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-frederic-cassel-ginza-mitsukoshi-23",
    "title": "Frederic Cassel Ginza Mitsukoshi",
    "region": "tokyo",
    "area": "Ginza",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "TBD",
    "rating": 3.88,
    "tags": [
      "Cake, sweets, chocolate",
      "Main tourist area",
      "Ginza"
    ],
    "note": "Inside Ginza Mitsukoshi.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130101/13116839/",
    "mapQuery": "Frederic Cassel Ginza Mitsukoshi, Ginza, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-katsu-pulipo-24",
    "title": "Katsu Pulipo",
    "region": "tokyo",
    "area": "Shinjuku / Kabukicho",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 8,000-9,999",
    "rating": 3.87,
    "tags": [
      "Tonkatsu, katsu-don",
      "Main tourist area",
      "Seibu-Shinjuku"
    ],
    "note": "Shinjuku visitor area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1304/A130401/13264309/",
    "mapQuery": "Katsu Pulipo, Shinjuku / Kabukicho, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-kibun-zushi-25",
    "title": "Kibun Zushi",
    "region": "tokyo",
    "area": "Asakusa",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "TBD",
    "rating": 3.69,
    "tags": [
      "Sushi",
      "Main tourist area",
      "Asakusa"
    ],
    "note": "Asakusa visitor core.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1311/A131102/13016811/",
    "mapQuery": "Kibun Zushi, Asakusa, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-sushi-ko-26",
    "title": "Sushi Ko",
    "region": "tokyo",
    "area": "Nihonbashi / Suitengumae",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "TBD",
    "rating": 3.67,
    "tags": [
      "Sushi",
      "Main tourist area",
      "Nihonbashi"
    ],
    "note": "Central Tokyo / Nihonbashi-adjacent.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1302/A130204/13071398/",
    "mapQuery": "Sushi Ko, Nihonbashi / Suitengumae, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-sushi-mikata-27",
    "title": "Sushi Mikata",
    "region": "tokyo",
    "area": "Mita / Tamachi",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 8,000-9,999",
    "rating": 3.66,
    "tags": [
      "Stand-up sushi, seafood, sushi",
      "Central, less touristy",
      "Mita"
    ],
    "note": "Central Minato but outside the usual first-time tourist clusters.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1314/A131402/13290333/",
    "mapQuery": "Sushi Mikata, Mita / Tamachi, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-kamayoshi-28",
    "title": "KAMAYOSHI",
    "region": "tokyo",
    "area": "Kanda / Awajicho",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Up to JPY 999",
    "rating": 3.84,
    "tags": [
      "Udon, curry udon, tempura",
      "Central, less touristy",
      "Awajicho"
    ],
    "note": "Matched from Kamayoshi Tempura; central but not a typical tourist cluster.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1310/A131002/13201863/",
    "mapQuery": "KAMAYOSHI, Kanda / Awajicho, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-tempura-shimomura-29",
    "title": "Tempura Shimomura",
    "region": "tokyo",
    "area": "Shin-Okachimachi / Kuramae",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 10,000-14,999",
    "rating": 3.79,
    "tags": [
      "Tempura",
      "Central, less touristy",
      "Shin-Okachimachi"
    ],
    "note": "East-side central detour near Kuramae/Ueno.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1311/A131101/13213663/",
    "mapQuery": "Tempura Shimomura, Shin-Okachimachi / Kuramae, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-kagurazaka-okawaya-30",
    "title": "Kagurazaka Okawaya",
    "region": "tokyo",
    "area": "Kagurazaka",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 6,000-7,999",
    "rating": 3.75,
    "tags": [
      "Soba, tempura",
      "Main tourist area",
      "Kagurazaka"
    ],
    "note": "Kagurazaka dining area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1309/A130905/13197727/",
    "mapQuery": "Kagurazaka Okawaya, Kagurazaka, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-ten-suke-31",
    "title": "Ten Suke",
    "region": "tokyo",
    "area": "Koenji / Suginami",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "TBD",
    "rating": 3.57,
    "tags": [
      "Tempura",
      "Outside main tourist area",
      "Koenji"
    ],
    "note": "West-side purpose trip.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1319/A131904/13010553/",
    "mapQuery": "Ten Suke, Koenji / Suginami, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-bam-bi-coffee-32",
    "title": "BAM BI COFFEE",
    "region": "tokyo",
    "area": "Shin-Okubo",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 1,000-1,999",
    "rating": 3.49,
    "tags": [
      "Cafe, pancake",
      "Main tourist area",
      "Shin-Okubo"
    ],
    "note": "Shin-Okubo food/cafe area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1304/A130404/13270013/",
    "mapQuery": "BAM BI COFFEE, Shin-Okubo, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-jackson-hole-33",
    "title": "JACKSON HOLE",
    "region": "tokyo",
    "area": "Chofu",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.51,
    "tags": [
      "Beer bar, American, hamburger",
      "Outside main tourist area",
      "Chofu"
    ],
    "note": "Far west Tokyo; dedicated detour.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1326/A132601/13023421/",
    "mapQuery": "JACKSON HOLE, Chofu, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-higuma-doughnuts-gakugei-daigaku-honten-34",
    "title": "HIGUMA Doughnuts Gakugei Daigaku Honten",
    "region": "tokyo",
    "area": "Gakugei Daigaku / Meguro",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 1,000-1,999",
    "rating": 3.55,
    "tags": [
      "Donut, hamburger, cafe",
      "Outside main tourist area",
      "Gakugei Daigaku"
    ],
    "note": "Residential/dining area south of central tourist loops.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1317/A131702/13225428/",
    "mapQuery": "HIGUMA Doughnuts Gakugei Daigaku Honten, Gakugei Daigaku / Meguro, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-koffee-mameya-35",
    "title": "KOFFEE MAMEYA",
    "region": "tokyo",
    "area": "Omotesando",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 1,000-1,999",
    "rating": 3.5,
    "tags": [
      "Coffee stand",
      "Main tourist area",
      "Omotesando"
    ],
    "note": "Omotesando visitor area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1306/A130602/13204760/",
    "mapQuery": "KOFFEE MAMEYA, Omotesando, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-onibus-coffee-nakameguro-36",
    "title": "ONIBUS COFFEE Nakameguro",
    "region": "tokyo",
    "area": "Nakameguro",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "Up to JPY 999",
    "rating": 3.58,
    "tags": [
      "Cafe",
      "Main tourist area",
      "Nakameguro"
    ],
    "note": "Nakameguro visitor/dining area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1317/A131701/13191293/",
    "mapQuery": "ONIBUS COFFEE Nakameguro, Nakameguro, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-sweet-check-37",
    "title": "Sweet Check",
    "region": "tokyo",
    "area": "Omotesando",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 1,000-1,999",
    "rating": 3.47,
    "tags": [
      "Cafe, omurice, cake",
      "Main tourist area",
      "Omotesando"
    ],
    "note": "Omotesando visitor area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1306/A130602/13293970/",
    "mapQuery": "Sweet Check, Omotesando, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-ramen-jazzy-beats-38",
    "title": "Ramen Jazzy Beats",
    "region": "tokyo",
    "area": "Nakameguro",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.67,
    "tags": [
      "Ramen",
      "Main tourist area",
      "Nakameguro"
    ],
    "note": "Nakameguro visitor/dining area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1317/A131701/13299883/",
    "mapQuery": "Ramen Jazzy Beats, Nakameguro, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-kagurazaka-cocochino-39",
    "title": "Kagurazaka Cocochino",
    "region": "tokyo",
    "area": "Kagurazaka / Iidabashi",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 4,000-4,999",
    "rating": 3.46,
    "tags": [
      "Italian, steak, pasta",
      "Main tourist area",
      "Iidabashi"
    ],
    "note": "Kagurazaka dining area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1309/A130905/13295441/",
    "mapQuery": "Kagurazaka Cocochino, Kagurazaka / Iidabashi, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-taizan-sheng-jian-ten-40",
    "title": "Taizan Sheng Jian Ten",
    "region": "tokyo",
    "area": "Jiyugaoka",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.49,
    "tags": [
      "Xiaolongbao / shengjian",
      "Outside main tourist area",
      "Jiyugaoka"
    ],
    "note": "Jiyugaoka is a pleasant detour outside first-time tourist loops.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1317/A131703/13101812/",
    "mapQuery": "Taizan Sheng Jian Ten, Jiyugaoka, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-dosanko-sakaba-morimachi-shigezo-yaesu-ten-41",
    "title": "Dosanko Sakaba Morimachi Shigezo Yaesu ten",
    "region": "tokyo",
    "area": "Yaesu / Tokyo Station",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 3,000-3,999",
    "rating": 3.43,
    "tags": [
      "Izakaya, seafood",
      "Main tourist area",
      "Nihombashi"
    ],
    "note": "Tabelog marks this Yaesu listing closed; verify before planning.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1302/A130201/13162451/",
    "mapQuery": "Dosanko Sakaba Morimachi Shigezo Yaesu ten, Yaesu / Tokyo Station, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-hamburg-omurice-no-omise-ikura-shibuya-ten-42",
    "title": "Hamburg & Omurice no Omise Ikura Shibuya ten",
    "region": "tokyo",
    "area": "Shibuya",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.42,
    "tags": [
      "Omurice, hamburger steak, yoshoku",
      "Main tourist area",
      "Shinsen"
    ],
    "note": "Shibuya visitor area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1303/A130301/13297345/",
    "mapQuery": "Hamburg & Omurice no Omise Ikura Shibuya ten, Shibuya, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-oyoppi-coffee-43",
    "title": "oyoppi coffee",
    "region": "tokyo",
    "area": "Shin-Okubo",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 1,000-1,999",
    "rating": 3.45,
    "tags": [
      "Cafe",
      "Main tourist area",
      "Shin-Okubo"
    ],
    "note": "Shin-Okubo food/cafe area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1304/A130404/13299337/",
    "mapQuery": "oyoppi coffee, Shin-Okubo, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-hyakunen-honpo-akihabara-souhonten-44",
    "title": "Hyakunen Honpo Akihabara souhonten",
    "region": "tokyo",
    "area": "Akihabara / Suehirocho",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Up to JPY 999",
    "rating": 3.6,
    "tags": [
      "Ramen, abura-soba, maze-soba, tsukemen",
      "Main tourist area",
      "Suehirocho"
    ],
    "note": "Akihabara visitor area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1311/A131101/13199049/",
    "mapQuery": "Hyakunen Honpo Akihabara souhonten, Akihabara / Suehirocho, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-ikoma-zushi-45",
    "title": "Ikoma Zushi",
    "region": "tokyo",
    "area": "Umegaoka / Setagaya",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "TBD",
    "rating": 3.43,
    "tags": [
      "Sushi, seafood, izakaya",
      "Outside main tourist area",
      "Umegaoka"
    ],
    "note": "Residential west-side detour.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1318/A131812/13011788/",
    "mapQuery": "Ikoma Zushi, Umegaoka / Setagaya, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-tokyo-butchers-kanda-honten-46",
    "title": "Tokyo Butchers Kanda honten",
    "region": "tokyo",
    "area": "Kanda",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 4,000-4,999",
    "rating": 3.49,
    "tags": [
      "Bar, bistro, izakaya",
      "Central, less touristy",
      "Kanda"
    ],
    "note": "Central business district stop.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1310/A131002/13136654/",
    "mapQuery": "Tokyo Butchers Kanda honten, Kanda, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-nihonbashi-ten-don-kaneko-hannosuke-honten-47",
    "title": "Nihonbashi Ten-don Kaneko Hannosuke Honten",
    "region": "tokyo",
    "area": "Nihonbashi",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Up to JPY 999",
    "rating": 3.53,
    "tags": [
      "Ten-don, bento, anago",
      "Main tourist area",
      "Mitsukoshimae"
    ],
    "note": "Nihonbashi / Tokyo Station-adjacent.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1302/A130202/13118694/",
    "mapQuery": "Nihonbashi Ten-don Kaneko Hannosuke Honten, Nihonbashi, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-sushi-ebisu-hana-ebisu-honten-48",
    "title": "Sushi Ebisu Hana Ebisu honten",
    "region": "tokyo",
    "area": "Ebisu",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 5,000-5,999",
    "rating": 3.42,
    "tags": [
      "Izakaya, sushi, seafood",
      "Main tourist area",
      "Ebisu"
    ],
    "note": "Ebisu dining area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1303/A130302/13293501/",
    "mapQuery": "Sushi Ebisu Hana Ebisu honten, Ebisu, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-chillmatic-hamburger-bistro-49",
    "title": "Chillmatic Hamburger & Bistro",
    "region": "tokyo",
    "area": "Shibuya / Shinsen",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 2,000-2,999",
    "rating": 3.66,
    "tags": [
      "Hamburger",
      "Main tourist area",
      "Shinsen"
    ],
    "note": "Shibuya-side stop.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1303/A130301/13304969/",
    "mapQuery": "Chillmatic Hamburger & Bistro, Shibuya / Shinsen, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-yakiniku-jumbo-hanare-50",
    "title": "Yakiniku Jumbo Hanare",
    "region": "tokyo",
    "area": "Hongo / Bunkyo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 15,000-19,999",
    "rating": 4.32,
    "tags": [
      "Yakiniku, tripe",
      "Central, less touristy",
      "Hongo Sanchome"
    ],
    "note": "Central but outside common first-time tourist clusters.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1310/A131004/13160962/",
    "mapQuery": "Yakiniku Jumbo Hanare, Hongo / Bunkyo, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-sennen-ramen-51",
    "title": "Sennen Ramen",
    "region": "tokyo",
    "area": "Chofu",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Up to JPY 999",
    "rating": 3.19,
    "tags": [
      "Ramen",
      "Outside main tourist area",
      "Chofu"
    ],
    "note": "Matched from Sen Sen Ramen; verify spelling/listing before planning.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1326/A132601/13005980/",
    "mapQuery": "Sennen Ramen, Chofu, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-tokyo-godaime-hanayama-udon-ginza-ten-52",
    "title": "Godaime Hanayama Udon Ginza ten",
    "region": "tokyo",
    "area": "Ginza / Higashi-Ginza",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 3,000-3,999",
    "rating": 3.65,
    "tags": [
      "Udon, izakaya, deep-fried foods",
      "Main tourist area",
      "Higashi-Ginza"
    ],
    "note": "Ginza visitor area.",
    "sourceUrl": "https://tabelog.com/en/tokyo/A1301/A130101/13200630/",
    "mapQuery": "Godaime Hanayama Udon Ginza ten, Ginza / Higashi-Ginza, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-menya-saimi-1",
    "title": "Menya Saimi",
    "region": "hokkaido",
    "area": "Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Up to JPY 999",
    "rating": 3.96,
    "tags": [
      "Ramen",
      "Outer Sapporo"
    ],
    "note": "Ramen; south/east of central Sapporo.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010303/1000018/",
    "mapQuery": "Menya Saimi, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-ichimonji-curry-ten-2",
    "title": "Ichimonji Curry Ten",
    "region": "hokkaido",
    "area": "Shiroishi, Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.9,
    "tags": [
      "Curry",
      "Outer Sapporo"
    ],
    "note": "Curry; east-side Sapporo detour.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010301/1024063/",
    "mapQuery": "Ichimonji Curry Ten, Shiroishi, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-teatro-di-massa-3",
    "title": "teatro di massa",
    "region": "hokkaido",
    "area": "Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Dinner JPY 10,000-14,999; lunch JPY 5,000-5,999",
    "rating": 3.78,
    "tags": [
      "Italian / fine dining",
      "Needs Pin"
    ],
    "note": "Confirmed above 3.5; add exact pin before relying on map directions.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010103/1045656/",
    "mapQuery": "teatro di massa, Sapporo, Hokkaido, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-sapporo-junren-sapporo-ten-4",
    "title": "Sapporo Junren Sapporo ten",
    "region": "hokkaido",
    "area": "Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Up to JPY 999",
    "rating": 3.76,
    "tags": [
      "Ramen",
      "Outer Sapporo"
    ],
    "note": "Ramen; south of central Sapporo.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010303/1000031/",
    "mapQuery": "Sapporo Junren Sapporo ten, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-japanese-ramen-noodle-lab-q-5",
    "title": "Japanese Ramen Noodle Lab Q",
    "region": "hokkaido",
    "area": "Central Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.75,
    "tags": [
      "Ramen",
      "Central Sapporo"
    ],
    "note": "Central Sapporo ramen.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010102/1057715/",
    "mapQuery": "Japanese Ramen Noodle Lab Q, Central Sapporo, Hokkaido, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-ramen-yoshi-6",
    "title": "Ramen Yoshi",
    "region": "hokkaido",
    "area": "Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Up to JPY 999",
    "rating": 3.73,
    "tags": [
      "Ramen",
      "Outer Sapporo"
    ],
    "note": "Ramen; east/south of central Sapporo.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010303/1007919/",
    "mapQuery": "Ramen Yoshi, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-itadakimasu-7",
    "title": "itadakimasu",
    "region": "hokkaido",
    "area": "Central Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Dinner JPY 5,000-5,999; lunch JPY 2,000-2,999",
    "rating": 3.71,
    "tags": [
      "Jingisukan",
      "Central Sapporo"
    ],
    "note": "Jingisukan near Susukino.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010103/1036161/",
    "mapQuery": "itadakimasu, Central Sapporo, Hokkaido, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-teishoku-meshiya-8",
    "title": "Teishoku meshiya",
    "region": "hokkaido",
    "area": "Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 3,000-3,999",
    "rating": 3.71,
    "tags": [
      "Set meals",
      "Outer Sapporo"
    ],
    "note": "West-side Sapporo stop.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010105/1009451/",
    "mapQuery": "Teishoku meshiya, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-teuchi-soba-no-taguto-9",
    "title": "Teuchi Soba no Taguto",
    "region": "hokkaido",
    "area": "Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.7,
    "tags": [
      "Soba",
      "Outer Sapporo"
    ],
    "note": "West-side Sapporo soba.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010204/1000649/",
    "mapQuery": "Teuchi Soba no Taguto, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-keyaki-susukino-honten-10",
    "title": "Keyaki Susukino Honten",
    "region": "hokkaido",
    "area": "Susukino",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.69,
    "tags": [
      "Ramen",
      "Central Sapporo"
    ],
    "note": "Susukino ramen.",
    "sourceUrl": "https://tabelog.com/hokkaido/A0101/A010103/1000150/",
    "mapQuery": "Keyaki Susukino Honten, Susukino, Hokkaido, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-patisserie-shiiya-11",
    "title": "Patisserie Shiiya",
    "region": "hokkaido",
    "area": "Sapporo",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "JPY 1,000-1,999",
    "rating": 3.69,
    "tags": [
      "Patisserie / cafe",
      "Outer Sapporo"
    ],
    "note": "West-side patisserie.",
    "sourceUrl": "https://tabelog.com/en/hokkaido/A0101/A010105/1000154/",
    "mapQuery": "Patisserie Shiiya, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-aigues-vives-12",
    "title": "Aigues Vives",
    "region": "hokkaido",
    "area": "Otaru",
    "category": "Coffee & sweets",
    "duration": 90,
    "defaultStart": "14:30",
    "cost": "Avg. JPY 2,000-2,999",
    "rating": 3.67,
    "tags": [
      "Bakery",
      "Otaru Side Trip"
    ],
    "note": "Bakery outside central Otaru/Sapporo.",
    "sourceUrl": "https://tabelog.com/en/hokkaido/A0106/A010601/1004949/",
    "mapQuery": "Aigues Vives, Otaru, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-univers-s-13",
    "title": "Univers S",
    "region": "hokkaido",
    "area": "Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Dinner JPY 5,000-5,999; lunch JPY 3,000-3,999",
    "rating": 3.72,
    "tags": [
      "French / bistro",
      "Outer Sapporo"
    ],
    "note": "West-side Sapporo bistro.",
    "sourceUrl": "https://tabelog.com/en/hokkaido/A0101/A010204/1060900/",
    "mapQuery": "Univers S, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-pot-au-feu-14",
    "title": "pot-au-feu",
    "region": "hokkaido",
    "area": "Kiyota, Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Lunch JPY 1,000-1,999",
    "rating": 3.72,
    "tags": [
      "Yoshoku",
      "Outer Sapporo"
    ],
    "note": "Kiyota Ward; further south/east from central Sapporo.",
    "sourceUrl": "https://tabelog.com/en/hokkaido/A0101/A010304/1001222/",
    "mapQuery": "pot-au-feu, Kiyota, Sapporo, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-tezukuri-hamburger-steak-kobo-toshi-15",
    "title": "Tezukuri Hamburger Steak Kobo Toshi",
    "region": "hokkaido",
    "area": "Central Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "JPY 1,000-1,999",
    "rating": 3.7,
    "tags": [
      "Hamburger steak",
      "Central Sapporo"
    ],
    "note": "Hamburger steak; selected Tabelog Yoshoku EAST 100 in 2025.",
    "sourceUrl": "https://tabelog.com/en/hokkaido/A0101/A010102/1009680/",
    "mapQuery": "Tezukuri Hamburger Steak Kobo Toshi, Central Sapporo, Hokkaido, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-yakitori-salt-16",
    "title": "Yakitori Salt",
    "region": "hokkaido",
    "area": "Central Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Dinner JPY 6,000-7,999",
    "rating": 3.62,
    "tags": [
      "Yakitori",
      "Central Sapporo"
    ],
    "note": "Yakitori; west of central core.",
    "sourceUrl": "https://tabelog.com/en/hokkaido/A0101/A010102/1063138/",
    "mapQuery": "Yakitori Salt, Central Sapporo, Hokkaido, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-kirin-17",
    "title": "Kirin",
    "region": "hokkaido",
    "area": "Central Sapporo",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Dinner JPY 2,000-2,999",
    "rating": 3.67,
    "tags": [
      "Dumpling / dim sum",
      "Central Sapporo"
    ],
    "note": "Dumpling/dim sum listing, not Kirin Beer Garden.",
    "sourceUrl": "https://tabelog.com/en/hokkaido/A0101/A010103/1047534/",
    "mapQuery": "Kirin, Central Sapporo, Hokkaido, Japan",
    "outsideCore": false,
    "sourceLabel": "Tabelog listing"
  },
  {
    "id": "food-hokkaido-kuki-zen-18",
    "title": "Kuki Zen",
    "region": "hokkaido",
    "area": "Otaru",
    "category": "Food",
    "duration": 90,
    "defaultStart": "18:00",
    "cost": "Dinner JPY 15,000-19,999; lunch JPY 6,000-7,999",
    "rating": 3.63,
    "tags": [
      "Sushi",
      "Otaru Side Trip"
    ],
    "note": "Sushi in Otaru.",
    "sourceUrl": "https://tabelog.com/en/hokkaido/A0106/A010601/1079613/",
    "mapQuery": "Kuki Zen, Otaru, Hokkaido, Japan",
    "outsideCore": true,
    "sourceLabel": "Tabelog listing"
  }
];
