(function () {
  "use strict";

  const sources = {
    tokyo: "https://www.gotokyo.org/en/see-and-do/attractions/",
    sapporo: "https://www.sapporo.travel/en/spot/",
    hokkaido: "https://www.visit-hokkaido.jp/en/spot/index.html",
    otaru: "https://otaru.gr.jp/enjoy",
    narita: "https://www.nrtk.jp/translate/index.php?lang=en",
    disney: "https://www.tokyodisneyresort.jp/en/tdr/calendar/202610/",
    teamlab: "https://www.teamlab.art/",
    ghibli: "https://www.ghibli-museum.jp/en/",
    warner: "https://www.wbstudiotour.jp/en/",
    sanrio: "https://en.puroland.jp/",
    royce: "https://www.royce.com/brand/contents/cacao-chocolate-town/",
    airport: "https://www.hokkaido-airports.com/en/new-chitose/spend/enjoy/",
    mitsui: "https://mitsui-shopping-park.com/mop/sapporo/english/",
    costco: "https://www.costco.co.jp/store-finder/Sapporo",
    uniqlo: "https://www.uniqlo.com/jp/en/shop/",
    gu: "https://www.gu-global.com/jp/en/shop/",
    choice: "https://www.choice-hotels.jp/suites/tokyobay/",
  };

  const sourceLabels = {
    [sources.tokyo]: "GO TOKYO",
    [sources.sapporo]: "Welcome to Sapporo",
    [sources.hokkaido]: "Hokkaido official tourism",
    [sources.otaru]: "Otaru Tourism Association",
    [sources.narita]: "Narita tourism",
    [sources.disney]: "Tokyo Disney Resort",
    [sources.teamlab]: "teamLab",
    [sources.ghibli]: "Ghibli Museum",
    [sources.warner]: "Warner Bros. Studio Tour",
    [sources.sanrio]: "Sanrio Puroland",
    [sources.royce]: "ROYCE",
    [sources.airport]: "New Chitose Airport",
    [sources.mitsui]: "Mitsui Outlet Park",
    [sources.costco]: "Costco Japan",
    [sources.uniqlo]: "UNIQLO",
    [sources.gu]: "GU",
    [sources.choice]: "Comfort Suites Tokyo Bay",
  };

  // id, title, region, area, category, minutes, start, cost, note, tags, source, map query
  const activityRows = [
    ["narita-shinshoji", "Naritasan Shinsho-ji Temple", "narita", "Narita", "Culture", 120, "09:00", "Free", "Explore the temple complex and large landscaped park before or after the airport rush.", "temple|history|garden|easy", sources.narita],
    ["narita-omotesando", "Narita Omotesando old town walk", "narita", "Narita", "Neighbourhood", 90, "11:00", "Free", "A traditional shopping street leading toward Naritasan, known for eel restaurants and snacks.", "street|shopping|traditional|easy", sources.narita],
    ["narita-park", "Naritasan Park", "narita", "Narita", "Nature", 75, "10:30", "Free", "Ponds, paths and early autumn colour behind the temple grounds.", "park|autumn|quiet|easy", sources.narita],
    ["narita-kawatoyo", "Kawatoyo Narita Airport dinner", "narita", "Narita Airport", "Food", 90, "18:30", "AUD 40-50 pp", "Saved Narita dinner idea. Its original 6 October timing now needs reconfirmation because that is the domestic transfer day.", "eel|dinner|saved|airport|date needed", "https://tabelog.com/en/chiba/A1204/A120401/12058179/"],
    ["narita-hotel-breakfast", "Hotel Nikko Narita breakfast", "narita", "Hotel Nikko Narita", "Food", 60, "05:30", "Flora and David package; Helen pays individually", "Breakfast on 6 October after the paid Nikko night and before the domestic flight to Sapporo. The hotel restaurant opens from 5am.", "breakfast|hotel|saved|early", "https://www.nikko-narita.com/english/", "Hotel Nikko Narita"],
    ["narita-sapporo-flight", "Domestic flight to Sapporo", "narita", "Tokyo area to New Chitose", "Flight", 120, "12:00", "Paid status and fare not recorded", "Confirmed for Tuesday 6 October. Add the airline, flight number, departure airport, exact departure and arrival times before placing it on the board; the two-hour duration is only a placeholder.", "confirmed|transfer|flight|time needed", sources.airport, "New Chitose Airport"],
    ["narita-observation", "Narita Airport observation decks", "narita", "Narita Airport", "View", 45, "16:30", "Free", "A low-effort plane-watching stop inside the airport terminals.", "airport|planes|view|easy", "https://www.narita-airport.jp/en/fun/view/"],
    ["narita-aeronautical", "Museum of Aeronautical Sciences", "narita", "Shibayama", "Museum", 150, "10:00", "Check admission", "Hands-on aviation museum close to Narita Airport, best reached by bus, taxi or car.", "planes|museum|family|indoor", "https://www.aeromuseum.or.jp/english/"],
    ["narita-sakura-no-yama", "Sakura-no-Yama Park", "narita", "Narita", "Nature", 75, "14:00", "Free", "Park and aircraft viewpoint near the runway. Useful with a car or taxi.", "planes|park|photo|outdoor", sources.narita],
    ["narita-sora-no-yu", "Sora no Yu Narita Airport Onsen", "narita", "Shibayama", "Relax", 150, "14:00", "Check day-use fee", "An onsen and rest option near the airport. Check tattoo and shuttle policies.", "onsen|relax|indoor|airport", "https://soranoyu.com/en/"],
    ["narita-aeon", "AEON Mall Narita", "narita", "Narita", "Shopping", 150, "13:00", "Free entry", "Practical shopping, groceries and casual dining near Narita city.", "mall|shopping|rainy day", "https://narita-aeonmall.com/"],
    ["narita-shisui", "Shisui Premium Outlets", "narita", "Shisui", "Shopping", 240, "10:00", "Free entry", "Large outlet centre between Narita Airport and central Chiba.", "outlet|shopping|detour", "https://www.premiumoutlets.co.jp/en/shisui/"],
    ["narita-boso", "Boso-no-Mura open-air museum", "narita", "Sakae", "Culture", 240, "10:00", "Check admission", "Historic buildings and craft demonstrations in a reconstructed Edo-period setting.", "history|craft|outdoor|detour", "https://www.chiba-muse.or.jp/MURA/english/"],

    ["tokyo-disneyland", "Tokyo Disneyland", "tokyo", "Tokyo Bay / Maihama", "Theme park", 720, "08:00", "PAID", "Paid tickets are fixed for Sunday 18 October. The 12-hour board entry is a full-day placeholder; adjust it when final park hours and travel timing are confirmed.", "paid|full day|booked|halloween|fixed date", sources.disney],
    ["tokyo-disneysea", "Tokyo DisneySea", "tokyo", "Tokyo Bay / Maihama", "Theme park", 720, "08:00", "Ticket required", "A separate full-day park. Do not confuse this with the paid Disneyland tickets in the workbook.", "full day|theme park|halloween", sources.disney],
    ["tokyo-ikspiari", "Ikspiari shopping and dining", "tokyo", "Tokyo Bay / Maihama", "Shopping", 150, "17:00", "Free entry", "An easy arrival-day or evening option beside Maihama Station.", "shopping|dinner|easy|disney area", "https://www.ikspiari.com/en/"],
    ["tokyo-kasai-park", "Kasai Rinkai Park", "tokyo", "Tokyo Bay", "Nature", 120, "15:00", "Free", "Waterfront paths, a large Ferris wheel and sunset views close to the Disney area.", "park|waterfront|sunset|easy", sources.tokyo],
    ["tokyo-sea-life", "Tokyo Sea Life Park", "tokyo", "Tokyo Bay", "Museum", 150, "10:00", "Check admission", "Aquarium in Kasai Rinkai Park, useful as a half-day near Tokyo Bay.", "aquarium|indoor|near disney", "https://www.tokyo-zoo.net/english/kasai/"],
    ["tokyo-shibuya-crossing", "Shibuya Scramble Crossing", "tokyo", "Shibuya", "Landmark", 45, "17:30", "Free", "See the crossing from street level, then pair it with Shibuya Sky or nearby shopping.", "iconic|evening|photo|easy", sources.tokyo],
    ["tokyo-hachiko", "Hachiko statue", "tokyo", "Shibuya", "Landmark", 20, "17:00", "Free", "A quick meeting-point stop outside Shibuya Station.", "iconic|photo|quick", sources.tokyo],
    ["tokyo-shibuya-sky", "Shibuya Sky", "tokyo", "Shibuya", "View", 90, "16:30", "Timed ticket", "Book a timed sunset slot early if that view matters to you.", "view|sunset|reservation|popular", "https://www.shibuya-scramble-square.com/sky/en/"],
    ["tokyo-shibuya-parco", "Shibuya PARCO", "tokyo", "Shibuya", "Anime & games", 150, "13:00", "Free entry", "Fashion, character stores and the Nintendo and Pokemon floors in one stop.", "anime|games|shopping|indoor", "https://shibuya.parco.jp/en/"],
    ["tokyo-nintendo", "Nintendo TOKYO", "tokyo", "Shibuya", "Anime & games", 75, "13:30", "Free entry", "Official Nintendo shop inside Shibuya PARCO. Entry controls can apply when busy.", "games|shopping|popular", "https://www.nintendo.com/jp/officialstore/"],
    ["tokyo-pokemon-shibuya", "Pokemon Center Shibuya", "tokyo", "Shibuya", "Anime & games", 60, "14:30", "Free entry", "Pokemon shop inside Shibuya PARCO, easy to combine with Nintendo TOKYO.", "anime|shopping|popular", "https://www.pokemon.co.jp/shop/en/pokecen/shibuya/"],
    ["tokyo-miyashita", "MIYASHITA PARK", "tokyo", "Shibuya", "Neighbourhood", 90, "15:00", "Free entry", "Rooftop park, shops and casual food between Shibuya and Harajuku.", "shopping|park|easy", sources.tokyo],
    ["tokyo-shibuya-center", "Shibuya Center-gai evening walk", "tokyo", "Shibuya", "Neighbourhood", 75, "18:30", "Free", "Neon streets, shops and casual dining after the crossing.", "night|street|shopping", sources.tokyo],
    ["tokyo-meiji-jingu", "Meiji Jingu", "tokyo", "Harajuku", "Culture", 120, "08:30", "Free", "A calm forest shrine visit before Harajuku becomes busy.", "shrine|forest|morning|easy", sources.tokyo],
    ["tokyo-takeshita", "Takeshita Street", "tokyo", "Harajuku", "Shopping", 90, "10:30", "Free entry", "Youth fashion, sweets and kawaii culture. Go earlier for lighter crowds.", "kawaii|fashion|crowds|shopping", sources.tokyo],
    ["tokyo-cat-street", "Cat Street", "tokyo", "Harajuku / Shibuya", "Shopping", 90, "12:00", "Free", "A relaxed fashion walk connecting Harajuku and Shibuya.", "fashion|street|shopping", sources.tokyo],
    ["tokyo-omotesando", "Omotesando architecture and shopping", "tokyo", "Omotesando", "Shopping", 120, "13:00", "Free", "Flagship stores, architecture and cafes along a tree-lined avenue.", "fashion|architecture|shopping", sources.tokyo],
    ["tokyo-yoyogi", "Yoyogi Park", "tokyo", "Harajuku", "Nature", 90, "15:00", "Free", "A spacious reset between Meiji Jingu, Harajuku and Shibuya.", "park|rest|outdoor|easy", sources.tokyo],
    ["tokyo-nezu-museum", "Nezu Museum and garden", "tokyo", "Aoyama", "Museum", 120, "10:00", "Check admission", "Japanese and East Asian art with a quiet garden near Omotesando.", "art|garden|quiet|indoor", "https://www.nezu-muse.or.jp/en/"],
    ["tokyo-ota-memorial", "Ota Memorial Museum of Art", "tokyo", "Harajuku", "Museum", 75, "11:00", "Check admission", "Compact ukiyo-e museum close to Takeshita Street.", "art|ukiyoe|indoor", "https://www.ukiyoe-ota-muse.jp/eng"],
    ["tokyo-shinjuku-gyoen", "Shinjuku Gyoen National Garden", "tokyo", "Shinjuku", "Nature", 150, "09:30", "Check admission", "Large formal gardens and greenhouse. Check closing day and last entry.", "garden|autumn|quiet|outdoor", "https://fng.or.jp/shinjuku/en/"],
    ["tokyo-met-observatory", "Tokyo Metropolitan Government observatory", "tokyo", "Shinjuku", "View", 75, "10:00", "Free", "Free city views from the western side of Shinjuku.", "view|free|indoor|easy", "https://www.yokoso.metro.tokyo.lg.jp/en/tenbou/"],
    ["tokyo-omoide", "Omoide Yokocho", "tokyo", "Shinjuku", "Neighbourhood", 75, "18:00", "Pay as you eat", "Tiny postwar-style food lanes near Shinjuku Station.", "food lanes|night|atmosphere", sources.tokyo],
    ["tokyo-golden-gai", "Golden Gai lanes", "tokyo", "Shinjuku", "Neighbourhood", 75, "20:00", "Pay as you go", "Atmospheric lanes of very small bars. Some venues have cover charges.", "nightlife|bars|late", sources.tokyo],
    ["tokyo-kabukicho", "Kabukicho neon walk", "tokyo", "Shinjuku", "Neighbourhood", 60, "19:00", "Free", "A lively evening walk; keep normal city awareness around touts.", "night|neon|street", sources.tokyo],
    ["tokyo-kabukicho-tower", "Tokyu Kabukicho Tower", "tokyo", "Shinjuku", "Entertainment", 120, "17:00", "Free entry", "Food hall, cinema, music and views in one vertical entertainment complex.", "indoor|night|food|entertainment", "https://www.tokyu-kabukicho-tower.jp/en/"],
    ["tokyo-shinjuku-cat", "Shinjuku 3D cat billboard", "tokyo", "Shinjuku", "Anime & games", 20, "17:30", "Free", "A quick animated billboard stop by the east exit.", "quick|screen|photo|fun", sources.tokyo],
    ["tokyo-sensoji", "Senso-ji Temple", "tokyo", "Asakusa", "Culture", 120, "08:00", "Free", "Visit early for a calmer Kaminarimon and temple approach.", "temple|history|morning|iconic", sources.tokyo],
    ["tokyo-nakamise", "Nakamise shopping street", "tokyo", "Asakusa", "Shopping", 75, "09:30", "Free entry", "Traditional snacks and souvenirs on the approach to Senso-ji.", "souvenirs|snacks|traditional", sources.tokyo],
    ["tokyo-asakusa-view", "Asakusa Culture Tourist Information Center view", "tokyo", "Asakusa", "View", 45, "10:30", "Free", "Free upper-floor view over Kaminarimon and Nakamise.", "view|free|easy", sources.tokyo],
    ["tokyo-kappabashi", "Kappabashi kitchenware street", "tokyo", "Asakusa / Ueno", "Shopping", 120, "11:00", "Free entry", "Knives, ceramics, cookware and realistic food models.", "shopping|kitchen|craft", sources.tokyo],
    ["tokyo-sumida-walk", "Sumida River walk", "tokyo", "Asakusa", "Nature", 75, "16:00", "Free", "Easy riverside views toward Tokyo Skytree.", "river|sunset|walk|easy", sources.tokyo],
    ["tokyo-river-cruise", "Sumida River cruise", "tokyo", "Asakusa / Odaiba", "Cruise", 120, "14:00", "Ticket required", "A scenic transfer between Asakusa and the bay. Check the current timetable.", "boat|waterfront|transit", "https://www.suijobus.co.jp/en/"],
    ["tokyo-kimono", "Asakusa kimono rental walk", "tokyo", "Asakusa", "Experience", 240, "09:00", "Reservation recommended", "Allow fitting time and check return deadlines before booking.", "kimono|photo|reservation|culture", sources.tokyo],
    ["tokyo-skytree", "Tokyo Skytree", "tokyo", "Oshiage", "View", 120, "15:30", "Timed ticket", "Observation decks with broad city views. Sunset slots are popular.", "view|iconic|reservation", "https://www.tokyo-skytree.jp/en/"],
    ["tokyo-solamachi", "Tokyo Solamachi", "tokyo", "Oshiage", "Shopping", 150, "12:30", "Free entry", "Large shopping and food complex at the foot of Skytree.", "shopping|food|indoor", "https://www.tokyo-solamachi.jp/en/"],
    ["tokyo-sumida-aquarium", "Sumida Aquarium", "tokyo", "Oshiage", "Museum", 120, "11:00", "Check admission", "Compact modern aquarium inside Tokyo Solamachi.", "aquarium|indoor|easy", "https://www.sumida-aquarium.com/en/"],
    ["tokyo-ueno-park", "Ueno Park", "tokyo", "Ueno", "Nature", 90, "09:00", "Free", "A museum-rich park with ponds, shrines and broad paths.", "park|museums|easy", sources.tokyo],
    ["tokyo-national-museum", "Tokyo National Museum", "tokyo", "Ueno", "Museum", 180, "09:30", "Check admission", "Japan's largest collection of Japanese art and cultural objects.", "history|art|indoor|major", "https://www.tnm.jp/?lang=en"],
    ["tokyo-nature-science", "National Museum of Nature and Science", "tokyo", "Ueno", "Museum", 180, "10:00", "Check admission", "Natural history, technology and a strong rainy-day option.", "science|museum|indoor", "https://www.kahaku.go.jp/english/"],
    ["tokyo-ueno-zoo", "Ueno Zoo", "tokyo", "Ueno", "Nature", 240, "09:30", "Check admission", "Large city zoo. Check current animal viewing arrangements before relying on one exhibit.", "zoo|outdoor|family", "https://www.tokyo-zoo.net/english/ueno/"],
    ["tokyo-ameyoko", "Ameyoko market streets", "tokyo", "Ueno", "Shopping", 120, "16:00", "Free entry", "Busy market lanes with snacks, seafood, clothing and discount shops.", "market|street food|shopping|crowds", sources.tokyo],
    ["tokyo-yanaka", "Yanaka Ginza and old Tokyo walk", "tokyo", "Yanaka", "Neighbourhood", 150, "14:00", "Free", "Low-rise lanes, small shops and a slower side of Tokyo.", "old tokyo|street|quiet", sources.tokyo],
    ["tokyo-nezu-shrine", "Nezu Shrine", "tokyo", "Nezu", "Culture", 90, "10:00", "Free", "Historic shrine with vermilion gates near Yanaka and Ueno.", "shrine|photo|quiet", sources.tokyo],
    ["tokyo-akihabara", "Akihabara arcade crawl", "tokyo", "Akihabara", "Anime & games", 180, "14:00", "Pay per game", "Mix classic arcades, crane games and rhythm games around Electric Town.", "games|arcade|anime|night", sources.tokyo],
    ["tokyo-radio-kaikan", "Akihabara Radio Kaikan", "tokyo", "Akihabara", "Anime & games", 120, "11:00", "Free entry", "Multi-floor anime, figures, cards and hobby shopping.", "anime|figures|shopping|indoor", "https://www.akihabara-radiokaikan.co.jp/"],
    ["tokyo-kanda-myojin", "Kanda Myojin Shrine", "tokyo", "Akihabara", "Culture", 75, "09:30", "Free", "Historic shrine with a modern connection to Akihabara's tech culture.", "shrine|anime|history", "https://www.kandamyoujin.or.jp/english/"],
    ["tokyo-yodobashi-akiba", "Yodobashi Akiba", "tokyo", "Akihabara", "Shopping", 120, "17:00", "Free entry", "Large electronics, camera and hobby store beside Akihabara Station.", "electronics|shopping|indoor", "https://www.yodobashi-akiba.com/"],
    ["tokyo-character-street", "Tokyo Character Street", "tokyo", "Tokyo Station", "Anime & games", 90, "11:30", "Free entry", "Character shops beneath Tokyo Station, useful in wet weather.", "characters|shopping|indoor|easy", "https://www.tokyoeki-1bangai.co.jp/en/tokyocharacterstreet/"],
    ["tokyo-pokemon-dx", "Pokemon Center Tokyo DX", "tokyo", "Nihonbashi", "Anime & games", 90, "13:00", "Free entry", "Large Pokemon shop near Tokyo Station and Nihonbashi.", "pokemon|shopping|indoor", "https://www.pokemon.co.jp/shop/en/pokecen/tokyodx/"],
    ["tokyo-imperial-east", "Imperial Palace East Gardens", "tokyo", "Marunouchi", "Nature", 150, "09:00", "Free", "Historic stonework, gardens and lawns. Check closure days before planning.", "garden|history|free|morning", "https://www.kunaicho.go.jp/e-event/higashigyoen02.html"],
    ["tokyo-station", "Tokyo Station Marunouchi facade", "tokyo", "Marunouchi", "Landmark", 60, "16:30", "Free", "See the restored red-brick station and Marunouchi plaza.", "architecture|photo|easy", sources.tokyo],
    ["tokyo-kitte", "KITTE rooftop garden", "tokyo", "Marunouchi", "View", 60, "17:30", "Free", "A close free view over Tokyo Station platforms and facade.", "view|free|sunset|easy", "https://marunouchi.jp-kitte.jp/guide/"],
    ["tokyo-marunouchi", "Marunouchi Naka-dori walk", "tokyo", "Marunouchi", "Neighbourhood", 75, "15:00", "Free", "Polished pedestrian-friendly avenue between Tokyo Station and Yurakucho.", "architecture|shopping|street", sources.tokyo],
    ["tokyo-jimbocho", "Jimbocho book town", "tokyo", "Jimbocho", "Shopping", 150, "11:00", "Free entry", "Second-hand books, prints, stationery and old-school curry shops.", "books|shopping|detour", sources.tokyo],
    ["tokyo-ginza-walk", "Ginza Chuo-dori", "tokyo", "Ginza", "Shopping", 120, "13:00", "Free", "Flagship fashion, architecture and department stores in Tokyo's polished retail district.", "fashion|shopping|architecture", sources.tokyo],
    ["tokyo-ginza-six", "GINZA SIX", "tokyo", "Ginza", "Shopping", 120, "14:00", "Free entry", "Luxury shopping, art installations and a rooftop garden.", "fashion|art|shopping|indoor", "https://ginza6.tokyo.e.abf.hp.transer.com/"],
    ["tokyo-ginza-mitsukoshi", "Ginza Mitsukoshi depachika", "tokyo", "Ginza", "Shopping", 90, "15:30", "Free entry", "Basement food halls for beautifully packed sweets and savoury food.", "food hall|shopping|sweets|indoor", "https://www.mistore.jp/store/ginza/foreign_customer.html"],
    ["tokyo-kabukiza", "Kabukiza theatre and gallery", "tokyo", "Ginza", "Culture", 120, "11:00", "Ticket varies", "See the theatre facade, gallery and single-act ticket options if available.", "theatre|culture|history", "https://www.kabukiweb.net/theatres/kabukiza/"],
    ["tokyo-art-aquarium", "Art Aquarium Museum Ginza", "tokyo", "Ginza", "Museum", 90, "13:00", "Timed ticket", "Immersive goldfish displays inside Ginza Mitsukoshi.", "art|aquarium|indoor|photo", "https://artaquarium.jp/en/"],
    ["tokyo-tsukiji", "Tsukiji Outer Market", "tokyo", "Tsukiji", "Food", 150, "08:00", "Pay as you eat", "Go in the morning for seafood, tamagoyaki and market snacks.", "market|breakfast|seafood|morning", "https://www.tsukiji.or.jp/english/"],
    ["tokyo-hamarikyu", "Hama-rikyu Gardens", "tokyo", "Shiodome", "Nature", 120, "10:00", "Check admission", "Tidal ponds, tea house and skyline views near Tsukiji.", "garden|tea|quiet|outdoor", "https://www.tokyo-park.or.jp/park/hama-rikyu/"],
    ["tokyo-toyosu-market", "Toyosu Market", "tokyo", "Toyosu", "Food", 150, "08:00", "Free entry", "Market observation areas and restaurant floors. Go early and check closure days.", "market|seafood|morning|indoor", "https://www.shijou.metro.tokyo.lg.jp/english/toyosu"],
    ["tokyo-teamlab-planets", "teamLab Planets", "tokyo", "Toyosu", "Art", 150, "11:00", "Timed ticket", "Immersive art experience with water areas. Timed booking is strongly recommended.", "digital art|reservation|indoor|popular", "https://www.teamlab.art/e/planets/"],
    ["tokyo-odaiba", "Odaiba waterfront walk", "tokyo", "Odaiba", "Neighbourhood", 120, "16:00", "Free", "Rainbow Bridge views, malls and a broad waterfront promenade.", "waterfront|sunset|walk", sources.tokyo],
    ["tokyo-miraikan", "Miraikan science museum", "tokyo", "Odaiba", "Museum", 180, "10:00", "Check admission", "Robotics, space, Earth systems and future technology.", "science|robots|indoor|museum", "https://www.miraikan.jst.go.jp/en/"],
    ["tokyo-small-worlds", "SMALL WORLDS Miniature Museum", "tokyo", "Ariake", "Museum", 150, "13:00", "Check admission", "Detailed miniature worlds, including space and Tokyo scenes.", "miniatures|indoor|photo", "https://smallworlds.jp/en/"],
    ["tokyo-divercity", "DiverCity and giant robot statue", "tokyo", "Odaiba", "Anime & games", 120, "17:00", "Free entry", "Shopping centre and a large transforming robot display outside.", "anime|shopping|photo|night", "https://mitsui-shopping-park.com/divercity-tokyo/en/"],
    ["tokyo-rainbow-bridge", "Rainbow Bridge promenade", "tokyo", "Tokyo Bay", "View", 120, "15:30", "Free", "Walk the pedestrian route for bay views. Check opening hours and weather.", "walk|view|outdoor|weather", sources.tokyo],
    ["tokyo-tower", "Tokyo Tower", "tokyo", "Shiba", "View", 120, "17:00", "Ticket required", "Classic Tokyo observation tower, especially photogenic after dark.", "view|iconic|night", "https://www.tokyotower.co.jp/en.html"],
    ["tokyo-zojoji", "Zojo-ji Temple", "tokyo", "Shiba", "Culture", 90, "15:30", "Free", "Historic temple with Tokyo Tower rising behind it.", "temple|photo|history", "https://www.zojoji.or.jp/en/"],
    ["tokyo-teamlab-borderless", "teamLab Borderless", "tokyo", "Azabudai Hills", "Art", 150, "10:30", "Timed ticket", "Large immersive digital art museum. Book a timed slot.", "digital art|reservation|indoor|popular", "https://www.teamlab.art/e/tokyo/"],
    ["tokyo-azabudai", "Azabudai Hills", "tokyo", "Azabudai", "Neighbourhood", 120, "13:30", "Free entry", "Modern architecture, gardens, shops and galleries near Tokyo Tower.", "architecture|shopping|art", "https://www.azabudai-hills.com/en/"],
    ["tokyo-mori-art", "Mori Art Museum", "tokyo", "Roppongi", "Museum", 150, "13:00", "Check exhibition ticket", "Contemporary art high above Roppongi. Exhibition dates and ticket bundles vary.", "art|indoor|view", "https://www.mori.art.museum/en/"],
    ["tokyo-city-view", "Roppongi Hills Tokyo City View", "tokyo", "Roppongi", "View", 90, "16:30", "Check admission", "City panorama from Roppongi. Check whether outdoor access is operating.", "view|sunset|night", "https://tcv.roppongihills.com/en/"],
    ["tokyo-national-art", "The National Art Center Tokyo", "tokyo", "Roppongi", "Museum", 150, "10:00", "Exhibition ticket varies", "Distinctive architecture and rotating exhibitions; the building itself is free to enter.", "art|architecture|indoor", "https://www.nact.jp/english/"],
    ["tokyo-design-sight", "21_21 DESIGN SIGHT", "tokyo", "Roppongi", "Museum", 120, "12:00", "Check admission", "Compact design museum in Tokyo Midtown.", "design|architecture|indoor", "https://www.2121designsight.jp/en/"],
    ["tokyo-sunshine-city", "Sunshine City", "tokyo", "Ikebukuro", "Shopping", 180, "11:00", "Free entry", "A useful all-weather hub for shops, character stores, aquarium and views near Hisoca.", "shopping|indoor|near hotel|easy", "https://sunshinecity.jp/en/"],
    ["tokyo-pokemon-mega", "Pokemon Center Mega Tokyo", "tokyo", "Ikebukuro", "Anime & games", 90, "12:00", "Free entry", "Large Pokemon store inside Sunshine City, close to the Ikebukuro hotel.", "pokemon|anime|shopping|near hotel", "https://www.pokemon.co.jp/shop/en/pokecen/megatokyo/"],
    ["tokyo-animate", "Animate Ikebukuro flagship", "tokyo", "Ikebukuro", "Anime & games", 150, "13:30", "Free entry", "Multi-floor anime, manga, music and merchandise flagship.", "anime|manga|shopping|near hotel", "https://www.animate.co.jp/en/shop/ikebukuro/"],
    ["tokyo-sunshine-aquarium", "Sunshine Aquarium", "tokyo", "Ikebukuro", "Museum", 120, "10:00", "Timed ticket may apply", "Rooftop-style urban aquarium inside Sunshine City.", "aquarium|indoor|near hotel", "https://sunshinecity.jp/en/aquarium/"],
    ["tokyo-otome-road", "Otome Road", "tokyo", "Ikebukuro", "Anime & games", 90, "16:00", "Free entry", "Anime and manga shops specialising in women-oriented fandoms.", "anime|manga|shopping|near hotel", sources.tokyo],
    ["tokyo-gashapon", "Gashapon Department Store Ikebukuro", "tokyo", "Ikebukuro", "Anime & games", 75, "15:00", "Pay per capsule", "A very large capsule-toy floor inside Sunshine City.", "games|collectibles|indoor|near hotel", "https://bandainamco-am.co.jp/others/gashapon-department-store/store/ikebukuro/"],
    ["tokyo-nakano-broadway", "Nakano Broadway", "tokyo", "Nakano", "Anime & games", 180, "12:00", "Free entry", "Dense retro anime, watches, toys and collectibles shopping.", "anime|retro|shopping|detour", sources.tokyo],
    ["tokyo-ghibli", "Ghibli Museum", "tokyo", "Mitaka", "Anime & games", 210, "10:00", "Advance ticket essential", "Tickets are date and time specific and can sell quickly. Pair with Kichijoji.", "anime|museum|reservation|day trip", sources.ghibli],
    ["tokyo-warner", "Warner Bros. Studio Tour Tokyo", "tokyo", "Nerima", "Theme park", 300, "10:00", "Advance ticket", "A long indoor studio experience. Book a timed entry and allow travel from central Tokyo.", "film|indoor|reservation|half day", sources.warner],
    ["tokyo-sanrio", "Sanrio Puroland", "tokyo", "Tama", "Theme park", 420, "09:30", "Advance ticket", "Indoor character theme park in western Tokyo. Treat it as a dedicated day trip.", "kawaii|theme park|indoor|day trip", sources.sanrio],
    ["tokyo-inokashira", "Inokashira Park", "tokyo", "Kichijoji", "Nature", 120, "13:30", "Free", "Lake, paths and relaxed neighbourhood atmosphere near the Ghibli Museum.", "park|walk|day trip|quiet", sources.tokyo],
    ["tokyo-kichijoji", "Kichijoji lanes and Harmonica Yokocho", "tokyo", "Kichijoji", "Neighbourhood", 150, "16:00", "Free", "Independent shops and tiny food lanes west of Shinjuku.", "shopping|food lanes|detour", sources.tokyo],
    ["tokyo-shimokitazawa", "Shimokitazawa vintage and music walk", "tokyo", "Shimokitazawa", "Shopping", 180, "13:00", "Free entry", "Vintage clothing, record shops, cafes and small theatres.", "vintage|music|shopping|detour", sources.tokyo],
    ["tokyo-nakameguro", "Nakameguro riverside walk", "tokyo", "Nakameguro", "Neighbourhood", 120, "15:00", "Free", "Independent shops and cafes along the Meguro River.", "river|cafes|walk|fashion", sources.tokyo],
    ["tokyo-daikanyama", "Daikanyama T-Site and backstreets", "tokyo", "Daikanyama", "Shopping", 120, "13:00", "Free entry", "Design-led bookshop complex and quiet fashion streets.", "books|design|shopping|quiet", sources.tokyo],
    ["tokyo-kagurazaka", "Kagurazaka lane walk", "tokyo", "Kagurazaka", "Neighbourhood", 120, "16:00", "Free", "Sloping streets, stone alleys, shrines and a strong dinner pairing.", "old tokyo|lanes|dinner", sources.tokyo],
    ["tokyo-koenji", "Koenji vintage and record shops", "tokyo", "Koenji", "Shopping", 150, "13:00", "Free entry", "A less polished, music-heavy alternative to Harajuku shopping.", "vintage|music|detour|shopping", sources.tokyo],
    ["tokyo-edo-open-air", "Edo-Tokyo Open Air Architectural Museum", "tokyo", "Koganei", "Museum", 240, "10:00", "Check admission", "Historic houses and shops relocated into a leafy park setting.", "architecture|history|outdoor|day trip", "https://www.tatemonoen.jp/english/"],
    ["tokyo-hokusai", "The Sumida Hokusai Museum", "tokyo", "Ryogoku", "Museum", 120, "10:00", "Check admission", "Modern museum focused on Hokusai's life and work.", "art|ukiyoe|indoor", "https://hokusai-museum.jp/?lang=en"],
    ["tokyo-fukagawa", "Fukagawa Edo Museum", "tokyo", "Kiyosumi-shirakawa", "Museum", 120, "11:00", "Check admission", "Walk-through reconstruction of an Edo neighbourhood.", "history|indoor|immersive", "https://www.kcf.or.jp/fukagawa/en/"],
    ["tokyo-kiyosumi", "Kiyosumi Gardens", "tokyo", "Kiyosumi-shirakawa", "Nature", 90, "14:00", "Check admission", "Compact strolling garden near excellent coffee stops.", "garden|quiet|coffee area", sources.tokyo],
    ["tokyo-mot", "Museum of Contemporary Art Tokyo", "tokyo", "Kiyosumi-shirakawa", "Museum", 180, "10:00", "Exhibition ticket varies", "Large contemporary art museum east of central Tokyo.", "art|indoor|architecture", "https://www.mot-art-museum.jp/eng/"],
    ["tokyo-koishikawa", "Koishikawa Korakuen Gardens", "tokyo", "Iidabashi", "Nature", 120, "09:30", "Check admission", "One of Tokyo's oldest landscape gardens, close to Tokyo Dome.", "garden|history|quiet", sources.tokyo],
    ["tokyo-rikugien", "Rikugien Gardens", "tokyo", "Komagome", "Nature", 120, "15:00", "Check admission", "Classical strolling garden. Peak colour is often later than the trip dates.", "garden|autumn|quiet|seasonal", sources.tokyo],
    ["tokyo-spa-laqua", "Spa LaQua", "tokyo", "Tokyo Dome", "Relax", 240, "15:00", "Check day-use fee", "Urban hot spring and relaxation complex. Check tattoo and entry policies.", "onsen|relax|indoor|rainy day", "https://www.laqua.jp/en/"],
    ["tokyo-dome-city", "Tokyo Dome City", "tokyo", "Korakuen", "Entertainment", 180, "14:00", "Pay per attraction", "Rides, shops and indoor entertainment in a central complex.", "rides|shopping|night|easy", "https://www.tokyo-dome.co.jp/en/tourists/"],
    ["tokyo-gotokuji", "Gotokuji Temple", "tokyo", "Setagaya", "Culture", 120, "10:00", "Free", "Temple associated with maneki-neko figures. Expect a suburban detour.", "temple|photo|detour", sources.tokyo],
    ["tokyo-tea-ceremony", "Tokyo tea ceremony experience", "tokyo", "Choose a district", "Experience", 120, "14:00", "Reservation required", "Choose a venue near the rest of your day and confirm accessibility and language support.", "tea|culture|reservation|indoor", sources.tokyo, "tea ceremony experience Tokyo"],
    ["tokyo-sushi-class", "Sushi-making class", "tokyo", "Choose a district", "Experience", 180, "11:00", "Reservation required", "A hands-on meal activity. Compare class location, menu and dietary support.", "food|class|reservation|indoor", sources.tokyo, "sushi making class Tokyo"],
    ["tokyo-karaoke", "Private karaoke session", "tokyo", "Shinjuku or Ikebukuro", "Entertainment", 120, "20:00", "Room fee varies", "Easy evening activity with private rooms and food ordering.", "music|night|indoor|fun", sources.tokyo, "karaoke Shinjuku Tokyo"],
    ["tokyo-mt-takao", "Mount Takao day trip", "tokyo", "Hachioji", "Day trip", 480, "07:30", "Transport plus optional cable car", "Popular accessible mountain day. Check trail conditions and allow for weekend crowds.", "hike|autumn|full day|outdoor", sources.tokyo],
    ["tokyo-kawagoe", "Kawagoe old town day trip", "tokyo", "Saitama", "Day trip", 420, "08:30", "Transport plus spending", "Warehouse streets, bell tower, sweets lane and temples north-west of Tokyo.", "history|shopping|full day", "https://www.koedo.or.jp/foreign/english/"],
    ["tokyo-kamakura", "Kamakura temples day trip", "tokyo", "Kanagawa", "Day trip", 540, "07:30", "Transport plus admissions", "Build a focused route around Hase, the Great Buddha, or Kita-Kamakura rather than rushing everything.", "temples|coast|full day|walking", "https://www.trip-kamakura.com/"],
    ["tokyo-enoshima", "Enoshima coast day trip", "tokyo", "Kanagawa", "Day trip", 540, "08:00", "Transport plus admissions", "Island shrines, sea views and caves. Best with clear, calm weather.", "coast|island|full day|weather", "https://www.fujisawa-kanko.jp/english/"],
    ["tokyo-yokohama", "Yokohama waterfront day trip", "tokyo", "Kanagawa", "Day trip", 480, "09:00", "Transport plus spending", "Combine Minato Mirai, Red Brick Warehouse and Chinatown.", "waterfront|shopping|full day", "https://www.yokohamajapan.com/"],
    ["tokyo-hakone", "Hakone day trip", "tokyo", "Kanagawa", "Day trip", 660, "07:00", "Transport pass plus admissions", "A long day for lake, ropeway and onsen scenery. Weather can obscure mountain views.", "onsen|mountains|full day|weather", "https://www.hakonenavi.jp/international/en/"],
    ["tokyo-nikko-day", "Nikko heritage day trip", "tokyo", "Tochigi", "Day trip", 660, "06:30", "Transport plus admissions", "A long but rewarding trip for ornate shrines and autumn scenery. Reserve limited-express seats if used.", "shrines|autumn|full day|long", "https://www.visitnikko.jp/en/"],

    ["sapporo-odori", "Odori Park autumn walk", "hokkaido", "Central Sapporo", "Nature", 90, "08:30", "Free", "The park is beside Grand Mercure and should begin showing autumn colour during the stay.", "autumn|park|near hotel|easy", sources.sapporo],
    ["sapporo-tv-tower", "Sapporo TV Tower", "hokkaido", "Odori", "View", 75, "17:00", "Check admission", "Central observation deck at the eastern end of Odori Park.", "view|night|central", sources.sapporo],
    ["sapporo-clock", "Sapporo Clock Tower", "hokkaido", "Central Sapporo", "Culture", 45, "10:00", "Check admission", "Compact historic landmark near Odori and Sapporo Station.", "history|central|easy", sources.sapporo],
    ["sapporo-red-brick", "Former Hokkaido Government Office", "hokkaido", "Central Sapporo", "Culture", 75, "10:30", "Check access", "The red-brick landmark and grounds between Odori and Sapporo Station.", "history|architecture|central", sources.sapporo],
    ["sapporo-shiryokan", "Sapporo Shiryokan", "hokkaido", "Odori west", "Museum", 75, "11:00", "Check admission", "Former Court of Appeals at the western edge of Odori Park, very close to the hotel.", "history|autumn|near hotel|indoor", sources.sapporo],
    ["sapporo-modern-art", "Hokkaido Museum of Modern Art", "hokkaido", "Nishi 18-chome", "Museum", 150, "10:00", "Exhibition ticket varies", "Major art museum within an easy walk or short subway ride from Grand Mercure.", "art|indoor|near hotel|rainy day", "https://artmuseum.pref.hokkaido.lg.jp/knb/english"],
    ["sapporo-nijo", "Nijo Market", "hokkaido", "Central Sapporo", "Food", 120, "08:00", "Pay as you eat", "Seafood market breakfast or lunch near Odori.", "market|seafood|breakfast|central", sources.sapporo],
    ["sapporo-tanukikoji", "Tanukikoji Shopping Arcade", "hokkaido", "Central Sapporo", "Shopping", 150, "14:00", "Free entry", "Covered arcade with shops, pharmacies, snacks and restaurants.", "shopping|indoor|central|rainy day", sources.sapporo],
    ["sapporo-susukino", "Susukino evening walk", "hokkaido", "Susukino", "Neighbourhood", 90, "18:30", "Free", "Neon entertainment district with abundant dinner options.", "night|food|central", sources.sapporo],
    ["sapporo-ramen-alley", "Ganso Ramen Yokocho", "hokkaido", "Susukino", "Food", 75, "19:00", "Pay as you eat", "A compact alley of ramen shops, convenient for a late dinner.", "ramen|night|central", sources.sapporo],
    ["sapporo-beer-museum", "Sapporo Beer Museum", "hokkaido", "Naebo", "Museum", 150, "13:00", "Tour and tasting vary", "Historic brewery museum. Book dining separately if pairing with a beer garden meal.", "beer|history|indoor", "https://www.sapporobeer.jp/english/brewery/s_museum/"],
    ["sapporo-shiroi-koibito", "Shiroi Koibito Park", "hokkaido", "Miyanosawa", "Experience", 210, "10:00", "Check admission", "Chocolate-themed factory park with displays, shops and seasonal gardens.", "chocolate|factory|indoor|shopping", "https://www.shiroikoibitopark.jp/en/"],
    ["sapporo-moiwa", "Mount Moiwa ropeway", "hokkaido", "Fushimi", "View", 150, "16:00", "Check ropeway fare", "Excellent autumn and night views. Check wind and operating status before travelling.", "view|autumn|sunset|weather", "https://mt-moiwa.jp/en/"],
    ["sapporo-jr-t38", "JR Tower Observatory T38", "hokkaido", "Sapporo Station", "View", 90, "17:00", "Check admission", "Indoor city view directly above Sapporo Station.", "view|night|indoor|central", "https://www.jr-tower.com/t38/english"],
    ["sapporo-aoao", "AOAO SAPPORO aquarium", "hokkaido", "Tanukikoji", "Museum", 120, "15:00", "Check admission", "Compact urban aquarium in the central shopping district.", "aquarium|indoor|central|rainy day", "https://aoao-sapporo.blue/en/"],
    ["sapporo-shrine", "Hokkaido Shrine", "hokkaido", "Maruyama", "Culture", 120, "09:00", "Free", "Forest shrine that pairs naturally with Maruyama Park and the zoo.", "shrine|forest|autumn|morning", sources.sapporo],
    ["sapporo-maruyama", "Maruyama Park autumn walk", "hokkaido", "Maruyama", "Nature", 90, "10:30", "Free", "Wooded paths and foliage close to Hokkaido Shrine.", "park|autumn|walk|easy", sources.sapporo],
    ["sapporo-zoo", "Maruyama Zoo", "hokkaido", "Maruyama", "Nature", 240, "10:00", "Check admission", "City zoo beside Maruyama Park. Check seasonal closing time.", "zoo|outdoor|half day", "https://www.city.sapporo.jp/zoo/english/"],
    ["sapporo-hokudai-ginkgo", "Hokkaido University ginkgo avenue", "hokkaido", "Hokkaido University", "Nature", 120, "09:00", "Free", "One of the best central autumn walks, with colour often building through October.", "ginkgo|autumn|photo|central", sources.sapporo],
    ["sapporo-hokudai-museum", "Hokkaido University Museum", "hokkaido", "Hokkaido University", "Museum", 120, "11:00", "Usually free; check", "Natural history and university collections on campus.", "museum|science|indoor|central", "https://www.museum.hokudai.ac.jp/english/"],
    ["sapporo-nakajima", "Nakajima Park", "hokkaido", "Nakajima Koen", "Nature", 120, "09:00", "Free", "Lakeside paths and strong autumn colour south of Susukino.", "park|autumn|photo|easy", sources.sapporo],
    ["sapporo-hoheikan", "Hoheikan historic guest house", "hokkaido", "Nakajima Park", "Culture", 60, "11:00", "Check admission", "Elegant Meiji-era building inside Nakajima Park.", "history|architecture|indoor", sources.sapporo],
    ["sapporo-moerenuma", "Moerenuma Park", "hokkaido", "Higashi Sapporo", "Nature", 240, "10:00", "Free", "Large Isamu Noguchi-designed landscape park. Allow travel time and check bicycle availability.", "design|park|outdoor|half day", "https://moerenumapark.jp/english/"],
    ["sapporo-historical-village", "Historical Village of Hokkaido", "hokkaido", "Atsubetsu", "Museum", 240, "10:00", "Check admission", "Open-air collection of historic Hokkaido buildings.", "history|outdoor|half day", "https://www.kaitaku.or.jp/en/"],
    ["sapporo-hokkaido-museum", "Hokkaido Museum", "hokkaido", "Atsubetsu", "Museum", 180, "10:00", "Check admission", "Hokkaido nature, history and Ainu culture, near the Historical Village.", "history|ainu|indoor|museum", "https://www.hm.pref.hokkaido.lg.jp/en/"],
    ["sapporo-art-park", "Sapporo Art Park", "hokkaido", "Minami Sapporo", "Art", 240, "10:00", "Admission varies", "Forest art complex with outdoor sculpture and autumn colour.", "art|autumn|outdoor|half day", "https://artpark.or.jp/en/"],
    ["sapporo-hill-buddha", "Hill of the Buddha", "hokkaido", "Makomanai", "Culture", 180, "10:00", "Check access", "Tadao Ando-designed landscape around a monumental Buddha. Combine with a southern Sapporo drive.", "architecture|photo|outdoor|car useful", "https://www.takinoreien.com/pages/108/"],
    ["sapporo-takino", "Takino Suzuran Hillside National Park", "hokkaido", "Minami Sapporo", "Nature", 300, "09:30", "Check admission", "Waterfalls, broad trails and foliage south of the city. Seasonal facilities vary.", "waterfalls|autumn|hike|half day", "https://www.takinopark.com/english/"],
    ["sapporo-hitsujigaoka", "Hitsujigaoka Observation Hill", "hokkaido", "Toyohira", "View", 120, "10:00", "Check admission", "Open views, the Clark statue and pastoral scenery.", "view|photo|outdoor", "https://www.hitsujigaoka.jp/en/"],
    ["sapporo-okurayama", "Okurayama Ski Jump and view", "hokkaido", "Miyanomori", "View", 150, "14:00", "Check lift fare", "Chairlift access to a high city viewpoint, weather permitting.", "view|sports|outdoor|weather", "https://okurayama-jump.jp/en/"],
    ["sapporo-olympic-museum", "Sapporo Olympic Museum", "hokkaido", "Miyanomori", "Museum", 120, "11:30", "Check admission", "Winter-sport history and interactive exhibits beside Okurayama.", "sports|museum|indoor", "https://sapporo-olympicmuseum.jp/english/"],
    ["sapporo-asahiyama", "Asahiyama Memorial Park", "hokkaido", "Chuo ward hills", "View", 90, "16:00", "Free", "Free hillside view over the city, attractive near sunset.", "view|sunset|autumn|outdoor", sources.sapporo],
    ["sapporo-fushimi-inari", "Sapporo Fushimi Inari Shrine", "hokkaido", "Fushimi", "Culture", 90, "10:00", "Free", "A local shrine with red gates on the lower slopes near Mount Moiwa.", "shrine|photo|outdoor", sources.sapporo],
    ["sapporo-factory", "Sapporo Factory", "hokkaido", "Central east", "Shopping", 150, "14:00", "Free entry", "Brick architecture, shops and indoor space near the original brewery area.", "shopping|architecture|indoor", "https://sapporofactory.jp/foreigner/"],
    ["sapporo-underground", "Chi-Ka-Ho underground walkway", "hokkaido", "Central Sapporo", "Shopping", 75, "12:00", "Free", "Weather-proof walk linking Sapporo Station and Odori.", "indoor|central|rainy day|easy", sources.sapporo],
    ["sapporo-pole-town", "Aurora Town and Pole Town", "hokkaido", "Odori / Susukino", "Shopping", 120, "13:00", "Free entry", "Underground shopping streets useful in rain or cold.", "shopping|indoor|central", sources.sapporo],
    ["sapporo-escon", "ES CON Field Hokkaido", "hokkaido", "Kitahiroshima", "Entertainment", 240, "11:00", "Tour or event ticket varies", "Modern ballpark and food complex outside Sapporo. Check non-game-day access and events.", "baseball|architecture|half day|outside city", "https://www.hkdballpark.com/en/"],
    ["sapporo-jozankei", "Jozankei Onsen day trip", "hokkaido", "Jozankei", "Relax", 480, "08:30", "Transport plus bathing", "Hot springs and valley foliage about an hour from central Sapporo.", "onsen|autumn|day trip|reservation", "https://jozankei.jp/en/"],
    ["sapporo-jozankei-footbath", "Jozankei footbath and village walk", "hokkaido", "Jozankei", "Relax", 180, "11:00", "Mostly free", "A lighter Jozankei option focused on foot baths, bridges and valley paths.", "onsen|walk|autumn|easy", "https://jozankei.jp/en/"],
    ["sapporo-hoheikyo-dam", "Hoheikyo Dam autumn trip", "hokkaido", "Jozankei", "Nature", 300, "09:00", "Transport required", "A major foliage spot. Seasonal access can be busy and may use an electric bus.", "autumn|view|day trip|seasonal", sources.sapporo],
    ["hokkaido-lake-shikotsu", "Lake Shikotsu day trip", "hokkaido", "Chitose", "Day trip", 480, "08:30", "Transport plus activities", "Clear caldera lake, lakeside walks and onsen south of Sapporo.", "lake|onsen|day trip|weather", sources.hokkaido],
    ["hokkaido-noboribetsu", "Noboribetsu Hell Valley", "hokkaido", "Noboribetsu", "Day trip", 540, "07:30", "Transport plus spending", "Volcanic valley and autumn forest trails. Combine with Oyunuma if conditions suit.", "volcanic|autumn|full day|walking", sources.hokkaido],
    ["hokkaido-oyunuma", "Oyunuma Pond and natural footbath", "hokkaido", "Noboribetsu", "Nature", 150, "11:30", "Free", "Forest extension to a Noboribetsu Hell Valley visit. Check trail conditions.", "onsen|forest|walk|weather", sources.hokkaido],
    ["hokkaido-upopoy", "Upopoy National Ainu Museum and Park", "hokkaido", "Shiraoi", "Museum", 300, "10:00", "Timed admission may apply", "National centre for learning about Ainu history and living culture.", "ainu|culture|museum|day trip", "https://ainu-upopoy.jp/en/"],
    ["hokkaido-lake-toya", "Lake Toya day trip", "hokkaido", "Toya", "Day trip", 600, "07:30", "Transport plus activities", "Lakeside scenery, onsen town and optional ropeway. A long Sapporo day.", "lake|onsen|full day|long", sources.hokkaido],
    ["hokkaido-usuzan", "Usuzan Ropeway", "hokkaido", "Lake Toya", "View", 180, "11:00", "Check ropeway fare", "Volcanic views over Lake Toya. Wind and cloud can affect operations.", "volcano|view|weather|day trip", "https://usuzan.hokkaido.jp/en/"],
    ["otaru-canal", "Otaru Canal walk", "hokkaido", "Otaru", "Neighbourhood", 120, "09:30", "Free", "Historic warehouses and canal views, especially atmospheric late afternoon.", "canal|history|day trip|photo", sources.otaru],
    ["otaru-sakaimachi", "Sakaimachi shopping street", "hokkaido", "Otaru", "Shopping", 180, "11:00", "Free entry", "Glassware, sweets, seafood and historic shopfronts.", "shopping|sweets|day trip|street", sources.otaru],
    ["otaru-letao", "LeTAO Main Store", "hokkaido", "Otaru", "Coffee & sweets", 75, "14:30", "Pay as you eat", "Flagship cheesecake and sweets stop near the Music Box Museum.", "cake|saved|shopping|day trip", "https://www.letao-brand.jp/en/"],
    ["otaru-music-box", "Otaru Music Box Museum", "hokkaido", "Otaru", "Shopping", 90, "13:00", "Free entry", "Historic building packed with music boxes near the end of Sakaimachi.", "music|shopping|history|day trip", "https://www.otaru-orgel.co.jp/english/"],
    ["otaru-kitaichi", "Kitaichi Glass", "hokkaido", "Otaru", "Shopping", 90, "12:00", "Free entry", "Otaru glassware and a lamp-lit cafe along Sakaimachi.", "glass|shopping|craft|day trip", "https://kitaichiglass.co.jp/en/"],
    ["otaru-glass-workshop", "Otaru glass-making workshop", "hokkaido", "Otaru", "Experience", 120, "13:30", "Reservation recommended", "Choose a workshop near Sakaimachi and confirm cooling or pickup time for the finished piece.", "craft|glass|reservation|day trip", sources.otaru, "glass making workshop Otaru Hokkaido"],
    ["otaru-art-base", "Otaru Art Base", "hokkaido", "Otaru", "Museum", 180, "10:00", "Check admission", "Art and stained glass in repurposed historic bank and warehouse buildings.", "art|architecture|indoor|day trip", "https://www.nitorihd.co.jp/otaru-art-base/en/"],
    ["otaru-bank-museum", "Bank of Japan Otaru Museum", "hokkaido", "Otaru", "Museum", 75, "11:00", "Free", "Financial history in a grand former bank building.", "history|architecture|free|day trip", "https://www3.boj.or.jp/otaru-m/eng/"],
    ["otaru-tengu", "Mount Tengu ropeway", "hokkaido", "Otaru", "View", 180, "15:30", "Check ropeway fare", "Sea and city view above Otaru. Check the 2026 seasonal schedule and wind.", "view|sunset|weather|day trip", "https://tenguyama.ckk.chuo-bus.co.jp/"],
    ["otaru-aquarium", "Otaru Aquarium", "hokkaido", "Shukutsu", "Museum", 240, "10:00", "Check admission", "Coastal aquarium north of central Otaru. Allow bus or driving time.", "aquarium|coast|half day|day trip", "https://otaru-aq.jp/"],
    ["otaru-canal-cruise", "Otaru Canal cruise", "hokkaido", "Otaru", "Cruise", 60, "16:00", "Ticket required", "Short canal cruise. Check October departures and weather on the day.", "boat|canal|reservation|day trip", "https://otaru.cc/en/"],
    ["otaru-blue-cave", "Otaru Blue Cave boat tour", "hokkaido", "Otaru coast", "Cruise", 150, "11:00", "Reservation required", "Sea conditions can cancel trips, so keep a land-based backup.", "boat|coast|weather|reservation", sources.otaru],
    ["otaru-sushi-street", "Otaru Sushi Street", "hokkaido", "Otaru", "Food", 120, "12:00", "Pay as you eat", "Choose one restaurant rather than treating the whole street as a single booking.", "sushi|seafood|day trip", sources.otaru],
    ["yoichi-nikka", "Nikka Whisky Yoichi Distillery", "hokkaido", "Yoichi", "Experience", 210, "10:00", "Reservation may be required", "Historic distillery west of Otaru. Check tour reservation and tasting rules.", "whisky|factory|reservation|day trip", "https://www.nikka.com/eng/distilleries/yoichi/"],
    ["yoichi-fruit", "Yoichi fruit orchard visit", "hokkaido", "Yoichi", "Nature", 180, "10:00", "Season and farm vary", "October harvest options depend on the orchard and season. Confirm picking availability.", "fruit|autumn|seasonal|day trip", sources.hokkaido],
    ["hokkaido-blue-pond", "Biei Blue Pond", "hokkaido", "Biei", "Day trip", 660, "06:30", "Long-distance transport", "A very long day from Sapporo. Best by car or organised tour with other Biei stops.", "photo|full day|long|weather", sources.hokkaido],
    ["hokkaido-shirahige", "Shirahige Falls", "hokkaido", "Biei", "Nature", 90, "12:00", "Free", "Turquoise waterfall near Shirogane Onsen, normally paired with Blue Pond.", "waterfall|photo|day trip|long", sources.hokkaido],
    ["hokkaido-shikisai", "Shikisai no Oka", "hokkaido", "Biei", "Nature", 120, "11:00", "Seasonal admission", "Panoramic farm landscape. October flower displays are season-dependent.", "farm|photo|seasonal|day trip", "https://www.shikisainooka.jp/en/"],
    ["hokkaido-ningle", "Ningle Terrace", "hokkaido", "Furano", "Shopping", 120, "16:00", "Free entry", "Forest craft village that is most atmospheric toward dusk.", "craft|forest|night|day trip", "https://www.princehotels.com/shinfurano/experience/ningle-terrace/"],
    ["hokkaido-cheese", "Furano Cheese Factory", "hokkaido", "Furano", "Experience", 120, "13:00", "Entry and workshops vary", "Factory viewing, tasting and optional food workshops.", "cheese|factory|food|day trip", "https://www.furano-cheese.jp/english/"],
    ["hokkaido-asahiyama-zoo", "Asahiyama Zoo", "hokkaido", "Asahikawa", "Day trip", 600, "07:00", "Transport plus admission", "A long day from Sapporo. Check autumn operating dates and hours carefully.", "zoo|full day|long|seasonal", "https://www.city.asahikawa.hokkaido.jp/asahiyamazoo/"],
    ["hokkaido-ramen-village", "Asahikawa Ramen Village", "hokkaido", "Asahikawa", "Food", 90, "13:00", "Pay as you eat", "Eight ramen shops in one complex, best paired with another Asahikawa stop.", "ramen|day trip|indoor", "https://www.ramenmura.com/"],
    ["hokkaido-asahidake", "Asahidake Ropeway", "hokkaido", "Daisetsuzan", "Day trip", 720, "05:30", "Long-distance transport plus ropeway", "High alpine conditions can be wintry by October. Only plan with current weather and transport checks.", "mountain|full day|weather|advanced", "https://asahidake.hokkaido.jp/en/"],
    ["hokkaido-sounkyo", "Sounkyo Gorge and ropeway", "hokkaido", "Daisetsuzan", "Day trip", 720, "05:30", "Long-distance transport", "A very long mountain day from Sapporo with seasonal weather risk.", "mountain|autumn|full day|advanced", "https://sounkyo.net/en/"],
    ["hokkaido-shakotan", "Cape Kamui and Shakotan coast", "hokkaido", "Shakotan", "Day trip", 600, "07:00", "Car or tour", "Dramatic coast west of Otaru. Wind and seasonal path closures can change the plan.", "coast|full day|car useful|weather", sources.hokkaido],
    ["hokkaido-royce-airport", "ROYCE Chocolate World", "hokkaido", "New Chitose Airport", "Shopping", 75, "13:00", "Free entry", "Chocolate displays and shopping in the airport. Keep it for arrival or departure time.", "chocolate|airport|saved|easy", sources.airport],
    ["hokkaido-airport-onsen", "New Chitose Airport Onsen", "hokkaido", "New Chitose Airport", "Relax", 180, "14:00", "Check day-use fee", "Useful for a long airport buffer. Check tattoo and baggage policies.", "onsen|airport|indoor|relax", sources.airport],
    ["hokkaido-doraemon", "Doraemon WAKUWAKU SKY PARK", "hokkaido", "New Chitose Airport", "Anime & games", 90, "12:00", "Check admission", "Character-themed play and shopping area in the airport.", "anime|airport|indoor|shopping", sources.airport],
    ["hokkaido-royce-town", "ROYCE Cacao & Chocolate Town", "hokkaido", "Tobetsu", "Experience", 240, "10:00", "Check admission", "Factory-style chocolate attraction outside Sapporo. Reserve if the official site requires it.", "chocolate|factory|saved|half day", sources.royce],
    ["hokkaido-mitsui-outlet", "Mitsui Outlet Park Sapporo Kitahiroshima", "hokkaido", "Kitahiroshima", "Shopping", 240, "10:00", "Free entry", "The main outlet-shopping stop requested for outside Sapporo.", "outlet|saved|shopping|half day", sources.mitsui],
    ["hokkaido-costco", "Costco Sapporo Warehouse", "hokkaido", "Kiyota / Kitahiroshima", "Shopping", 150, "14:00", "Membership required", "The Costco close to Mitsui Outlet Park, useful in the same driving loop.", "costco|saved|shopping|car useful", sources.costco],
    ["hokkaido-uniqlo", "UNIQLO Sapporo Tokyu", "hokkaido", "Sapporo Station", "Shopping", 90, "11:00", "Free entry", "Convenient central UNIQLO near Sapporo Station.", "uniqlo|saved|shopping|central", sources.uniqlo],
    ["hokkaido-gu", "GU Sapporo PIVOT CROSS", "hokkaido", "Odori", "Shopping", 90, "13:00", "Free entry", "Central GU near Odori and Susukino.", "gu|saved|shopping|central", sources.gu],
    ["hokkaido-car-rental", "Car rental pickup or return", "hokkaido", "Location to confirm", "Logistics", 60, "09:00", "AUD 617 total", "Cost is in the workbook and split equally between Flora and David, and Helen. Dates and depot are still unassigned.", "costed|needs details|car|logistics", sources.hokkaido],
    ["sapporo-tokyo-flight", "Domestic flight back to Tokyo", "hokkaido", "New Chitose to Tokyo area", "Flight", 120, "12:00", "Paid status and fare not recorded", "Expected on Wednesday 14 October for the move to Comfort Suites Tokyo Bay. Add the airline, flight number, destination airport and exact times before placing it on the board; the two-hour duration is only a placeholder.", "transfer|flight|time needed", sources.airport, "New Chitose Airport"],
  ];

  const activities = activityRows.map((row) => {
    const [id, title, region, area, category, duration, defaultStart, cost, note, tagString, sourceUrl, customMapQuery] = row;
    return {
      id,
      title,
      region,
      area,
      category,
      duration,
      defaultStart,
      cost,
      note,
      tags: tagString.split("|"),
      sourceUrl,
      sourceLabel: sourceLabels[sourceUrl] || (sourceUrl && sourceUrl.includes("tabelog.com") ? "Tabelog listing" : "Official site"),
      mapQuery: customMapQuery || `${title}, ${area}, Japan`,
      outsideCore: tagString.includes("day trip") || tagString.includes("detour") || tagString.includes("outside city") || tagString.includes("long"),
      fixedDate: id === "tokyo-disneyland" ? "2026-10-18" : null,
    };
  });

  const days = [
    { date: "2026-10-05", short: "Mon 5", label: "Monday 5 October", location: "Narita arrival", allowedRegions: ["narita"], lodging: "Hotel Nikko Narita, paid", alert: "MH070 reaches Narita at 18:05, followed by the one paid night at Hotel Nikko Narita.", tone: "arrival" },
    { date: "2026-10-06", short: "Tue 6", label: "Tuesday 6 October", location: "Narita to Sapporo", allowedRegions: ["narita", "hokkaido"], lodging: "Grand Mercure Sapporo Odori Park, paid", alert: "Domestic flight to Sapporo and Grand Mercure check-in today. Hotel stay confirmed for 6-14 October. Airline, flight number and exact transfer times are still needed; adjust the estimated check-in time after confirming arrival.", tone: "transfer" },
    { date: "2026-10-07", short: "Wed 7", label: "Wednesday 7 October", location: "Sapporo / Hokkaido", allowedRegions: ["hokkaido"], lodging: "Grand Mercure Sapporo Odori Park, paid", tone: "hokkaido" },
    { date: "2026-10-08", short: "Thu 8", label: "Thursday 8 October", location: "Sapporo / Hokkaido", allowedRegions: ["hokkaido"], lodging: "Grand Mercure Sapporo Odori Park, paid", tone: "hokkaido" },
    { date: "2026-10-09", short: "Fri 9", label: "Friday 9 October", location: "Sapporo / Hokkaido", allowedRegions: ["hokkaido"], lodging: "Grand Mercure Sapporo Odori Park, paid", tone: "hokkaido" },
    { date: "2026-10-10", short: "Sat 10", label: "Saturday 10 October", location: "Sapporo / Hokkaido", allowedRegions: ["hokkaido"], lodging: "Grand Mercure Sapporo Odori Park, paid", tone: "hokkaido" },
    { date: "2026-10-11", short: "Sun 11", label: "Sunday 11 October", location: "Sapporo / Hokkaido", allowedRegions: ["hokkaido"], lodging: "Grand Mercure Sapporo Odori Park, paid", tone: "hokkaido" },
    { date: "2026-10-12", short: "Mon 12", label: "Monday 12 October", location: "Sapporo / Hokkaido", allowedRegions: ["hokkaido"], lodging: "Grand Mercure Sapporo Odori Park, paid", tone: "hokkaido" },
    { date: "2026-10-13", short: "Tue 13", label: "Tuesday 13 October", location: "Sapporo / Hokkaido", allowedRegions: ["hokkaido"], lodging: "Grand Mercure Sapporo Odori Park, paid", tone: "hokkaido" },
    { date: "2026-10-14", short: "Wed 14", label: "Wednesday 14 October", location: "Sapporo to Tokyo Bay", allowedRegions: ["hokkaido", "tokyo"], lodging: "Comfort Suites Tokyo Bay, paid", alert: "Domestic flight back to the Tokyo area is expected today. Airline, airports, flight number and exact times are still needed to block the board correctly.", tone: "transfer" },
    { date: "2026-10-15", short: "Thu 15", label: "Thursday 15 October", location: "Tokyo Bay / Urayasu", allowedRegions: ["tokyo"], lodging: "Comfort Suites Tokyo Bay, paid", tone: "tokyo-bay" },
    { date: "2026-10-16", short: "Fri 16", label: "Friday 16 October", location: "Tokyo Bay / Urayasu", allowedRegions: ["tokyo"], lodging: "Comfort Suites Tokyo Bay, paid", tone: "tokyo-bay" },
    { date: "2026-10-17", short: "Sat 17", label: "Saturday 17 October", location: "Tokyo Bay to Ikebukuro", allowedRegions: ["tokyo"], lodging: "hotel hisoca ikebukuro, paid", alert: "Hotel change day. Keep luggage and the cross-city transfer in mind when timing activities.", tone: "tokyo" },
    { date: "2026-10-18", short: "Sun 18", label: "Sunday 18 October", location: "Tokyo Disneyland / Maihama", allowedRegions: ["tokyo"], lodging: "hotel hisoca ikebukuro, paid", alert: "Paid Tokyo Disneyland tickets are fixed for today. A full-day placeholder is on the board; adjust its hours once the final travel plan is confirmed.", tone: "tokyo-bay", recommendedForDisney: true },
    { date: "2026-10-19", short: "Mon 19", label: "Monday 19 October", location: "Narita departure", allowedRegions: ["narita"], lodging: "Overnight flight", alert: "MH089 departs Narita Terminal 2 at 10:05. Keep this morning clear for airport travel and check-in.", tone: "departure" },
    { date: "2026-10-20", short: "Tue 20", label: "Tuesday 20 October", location: "Perth arrival", allowedRegions: [], lodging: "Home", alert: "MH127 arrives Perth Terminal 1 at 01:10.", tone: "home" },
  ];

  const lockedItems = [
    { id: "mh126", date: "2026-10-05", start: "02:10", end: "08:00", title: "MH126 Perth to Kuala Lumpur", subtitle: "Malaysia Airlines, Business, PER T1 to KUL T1", category: "Flight" },
    { id: "mh070", date: "2026-10-05", start: "09:50", end: "18:05", title: "MH070 Kuala Lumpur to Narita", subtitle: "Malaysia Airlines, Business, KUL T1 to NRT T2", category: "Flight" },
    { id: "mh089", date: "2026-10-19", start: "10:05", end: "16:45", title: "MH089 Narita to Kuala Lumpur", subtitle: "Malaysia Airlines, Business, NRT T2 to KUL T1", category: "Flight" },
    { id: "mh127", date: "2026-10-19", start: "19:30", end: "01:10 +1", title: "MH127 Kuala Lumpur to Perth", subtitle: "Malaysia Airlines, Business, KUL T1 to PER T1", category: "Flight" },
    { id: "perth-arrival", date: "2026-10-20", start: "01:10", end: "01:10", title: "Arrive Perth", subtitle: "Perth Airport Terminal 1", category: "Arrival" },
  ];

  const starterSchedule = {
    "2026-10-06": [
      { uid: "starter-nikko-breakfast", activityId: "narita-hotel-breakfast", start: "05:30", duration: 60, notes: "Breakfast before the confirmed domestic transfer to Sapporo." },
    ],
    "2026-10-18": [
      { uid: "starter-disneyland", activityId: "tokyo-disneyland", start: "08:00", duration: 720, notes: "Paid tickets confirmed for Sunday 18 October. Adjust the hours when the final park and travel timing is known." },
    ],
  };

  const floatingItems = [
    { id: "domestic-sapporo-flight-details", activityId: "narita-sapporo-flight", label: "Confirmed date, times needed", detail: "Domestic transfer is Tuesday 6 October. Add the airline, flight number and exact departure/arrival times before scheduling it.", suggestedDates: ["2026-10-06"] },
    { id: "domestic-tokyo-flight-details", activityId: "sapporo-tokyo-flight", label: "Return details needed", detail: "The Sapporo to Tokyo transfer belongs on Wednesday 14 October. Add the airline, airports, flight number and exact times before scheduling it.", suggestedDates: ["2026-10-14"] },
    { id: "paid-disneyland", activityId: "tokyo-disneyland", label: "Paid, fixed for 18 October", detail: "Flora and David JPY 21,400; Helen JPY 9,500", suggestedDates: ["2026-10-18"] },
    { id: "car-rental-details", activityId: "hokkaido-car-rental", label: "Dates needed", detail: "AU$617 total, split AU$308.50 per payer group", suggestedDates: ["2026-10-08", "2026-10-09", "2026-10-10", "2026-10-11", "2026-10-12", "2026-10-13"] },
  ];

  const hotels = [
    { name: "Hotel Nikko Narita", dates: "5-6 Oct", status: "Paid", people: "One night. Flora and David: Comfort King with breakfast; Helen: Comfort King without breakfast", mapQuery: "Hotel Nikko Narita", sourceUrl: "https://www.nikko-narita.com/english/" },
    { name: "Grand Mercure Sapporo Odori Park", dates: "6-14 Oct (8 nights)", status: "Paid", people: "Flora and David: Classic King with Lounge; Helen: Superior Twin with Lounge", mapQuery: "Grand Mercure Sapporo Odori Park", sourceUrl: "https://all.accor.com/hotel/C0X7/index.en.shtml" },
    { name: "Comfort Suites Tokyo Bay", dates: "14-17 Oct", status: "Paid", people: "Two nonsmoking suites with two double beds", mapQuery: "Comfort Suites Tokyo Bay", sourceUrl: sources.choice },
    { name: "hotel hisoca ikebukuro", dates: "17-19 Oct", status: "Paid", people: "Two Standard Double DS rooms with dry sauna", mapQuery: "hotel hisoca ikebukuro", sourceUrl: "https://hotelhisoca.com/" },
  ];

  window.TRIP_DATA = {
    version: 1,
    title: "Japan Autumn Itinerary",
    dates: "5-20 October 2026",
    travellers: ["Flora", "David", "Helen"],
    workbook: {
      file: "Japan Trip Cost Planner - Disneyland Paid Added.xlsx",
      totalAud: 17993.41,
      floraDavidAud: 10899.88,
      helenAud: 7093.53,
      airfareAud: 10413.63,
      hotelAud: 6653.78,
      disneyJpy: 30900,
      carRentalAud: 617,
    },
    days,
    lockedItems,
    starterSchedule,
    floatingItems,
    hotels,
    sources,
    activities: [...activities, ...(window.RESTAURANT_DATA || []), ...(window.EXTRA_ACTIVITIES || [])],
  };
})();
